<?php if ( ! empty($this->user)): ?>
    <?php $user = $this->user; ?>
    <?php $userPlanning = $this->usersPlanning[$user['id']]; ?>

<div class="user-planning" id="user_planning_<?php echo $user['id']; ?>" data-user="<?php echo $user['id']; ?>" data-group="<?php echo $this->group['id']; ?>">
    <h2 class="user-planning-header">User: <?php echo $user['full_name']; ?> (<?php echo $user['email']; ?>)</h2>
    <table class="table table-bordered user-planning-weeks">
        <thead>
        <tr>
            <th class="span2">
                Maandag
            </th>
            <th class="span2">
                Dinsdag
            </th>
            <th class="span2">
                Dinsdag
            </th>
            <th class="span2">
                Donderdag
            </th>
            <th class="span2">
                Vrijdag
            </th>
            <th class="span2">
                Zaterdag
            </th>
            <th class="span2">
                Zondag
            </th>
        </tr>
        </thead>
        <tbody>
        <!-- START ODD WEEK -->
        <tr class="odd-week-row">
            <?php foreach ($this->weekDays['odd'] as $key => $day): ?>
            <td class="week-day">
                <form class="form-inline form-user-planning-day" data-week-type="odd" data-day-number="<?php echo $day['day_number']; ?>">
                    <?php
                    if ( ! empty($userPlanning[$key])) {
                        $data = $userPlanning[$key];
                        $checked = ((bool)$data['enabled']) ? 'checked="checked"' : '';

                        $startTime = new DateTime($data['time_start']);
                        $startHourValue = $startTime->format('H');
                        $startMinValue  = $startTime->format('i');

                        $endTime = new DateTime($data['time_end']);
                        $endHourValue = $endTime->format('H');
                        $endMinValue  = $endTime->format('i');

                        $pauseStartTime = new DateTime($data['pause_start']);
                        $pauseStartHourValue = $pauseStartTime->format('H');
                        $pauseStartMinValue  = $pauseStartTime->format('i');

                        $pauseEndTime = new DateTime($data['pause_end']);
                        $pauseEndHourValue = $pauseEndTime->format('H');
                        $pauseEndMinValue  = $pauseEndTime->format('i');
                    } else {
                        $checked = '';
                        $startHourValue = '';
                        $startMinValue  = '';
                        $endHourValue = '';
                        $endMinValue  = '';
                        $pauseStartHourValue = '';
                        $pauseStartMinValue  = '';
                        $pauseEndHourValue = '';
                        $pauseEndMinValue  = '';
                    }
                    ?>
                    <div class="work-time">
                        <div class="input-time">
                            <input type="text" value="<?php echo $startHourValue; ?>" name="start_hour" class="set-time-hour start-hour"><?php
                            ?>:<?php
                            ?><input type="text" value="<?php echo $startMinValue; ?>" name="start_min" class="set-time-min start-min">
                        </div>
                        <div class="separator">Work</div>
                        <div class="input-time">
                            <input type="text" value="<?php echo $endHourValue; ?>" name="end_hour" class="set-time-hour end-hour"><?php
                            ?>:<?php
                            ?><input type="text" value="<?php echo $endMinValue; ?>" name="end_min" class="set-time-min end-min">
                        </div>
                    </div>
                    <div class="enable-flag-container">
                        <input type="checkbox" name="enable_day" value="1" class="enable-day" <?php echo $checked; ?>>
                    </div>
                    <div class="pause-time">
                        <div class="input-time">
                            <input type="text" value="<?php echo $pauseStartHourValue; ?>" class="pause-hour set-time-hour start-hour"><?php
                            ?>:<?php
                            ?><input type="text" value="<?php echo $pauseStartMinValue; ?>" class="pause-min set-time-min start-min">
                        </div>
                        <div class="separator">Pause</div>
                        <div class="input-time">
                            <input type="text" value="<?php echo $pauseEndHourValue; ?>" class="pause-hour set-time-hour end-hour"><?php
                            ?>:<?php
                            ?><input type="text" value="<?php echo $pauseEndMinValue; ?>" class="pause-min set-time-min end-min">
                        </div>
                    </div>
                </form>
            </td>
            <?php endforeach; ?>
        </tr>
        <!-- END ODD WEEK -->
        <!-- STERT EVEN WEEK -->
        <tr class="even-week-row">
            <?php foreach ($this->weekDays['even'] as $key => $day): ?>
            <td class="week-day">
                <form class="form-inline form-user-planning-day" data-week-type="even" data-day-number="<?php echo $day['day_number']; ?>">
                    <?php
                    if ( ! empty($userPlanning[$key])) {
                        $data = $userPlanning[$key];
                        $checked = ((bool)$data['enabled']) ? 'checked="checked"' : '';

                        $startTime = new DateTime($data['time_start']);
                        $startHourValue = $startTime->format('H');
                        $startMinValue  = $startTime->format('i');

                        $endTime = new DateTime($data['time_end']);
                        $endHourValue = $endTime->format('H');
                        $endMinValue  = $endTime->format('i');

                        $pauseStartTime = new DateTime($data['pause_start']);
                        $pauseStartHourValue = $pauseStartTime->format('H');
                        $pauseStartMinValue  = $pauseStartTime->format('i');

                        $pauseEndTime = new DateTime($data['pause_end']);
                        $pauseEndHourValue = $pauseEndTime->format('H');
                        $pauseEndMinValue  = $pauseEndTime->format('i');
                    } else {
                        $checked = '';
                        $startHourValue = '';
                        $startMinValue  = '';
                        $endHourValue = '';
                        $endMinValue  = '';
                        $pauseStartHourValue = '';
                        $pauseStartMinValue  = '';
                        $pauseEndHourValue = '';
                        $pauseEndMinValue  = '';
                    }
                    ?>
                    <div class="work-time">
                        <div class="input-time">
                            <input type="text" value="<?php echo $startHourValue; ?>" name="start_hour" class="set-time-hour start-hour"><?php
                            ?>:<?php
                            ?><input type="text" value="<?php echo $startMinValue; ?>" name="start_min" class="set-time-min start-min">
                        </div>
                        <div class="separator">Work</div>
                        <div class="input-time">
                            <input type="text" value="<?php echo $endHourValue; ?>" name="end_hour" class="set-time-hour end-hour"><?php
                            ?>:<?php
                            ?><input type="text" value="<?php echo $endMinValue; ?>" name="end_min" class="set-time-min end-min">
                        </div>
                    </div>
                    <div class="enable-flag-container">
                        <input type="checkbox" name="enable_day" value="1" class="enable-day" <?php echo $checked; ?>>
                    </div>
                    <div class="pause-time">
                        <div class="input-time">
                            <input type="text" value="<?php echo $pauseStartHourValue; ?>" class="pause-hour set-time-hour start-hour"><?php
                            ?>:<?php
                            ?><input type="text" value="<?php echo $pauseStartMinValue; ?>" class="pause-min set-time-min start-min">
                        </div>
                        <div class="separator">Pause</div>
                        <div class="input-time">
                            <input type="text" value="<?php echo $pauseEndHourValue; ?>" class="pause-hour set-time-hour end-hour"><?php
                            ?>:<?php
                            ?><input type="text" value="<?php echo $pauseEndMinValue; ?>" class="pause-min set-time-min end-min">
                        </div>
                    </div>
                </form>
            </td>
            <?php endforeach; ?>
        </tr>
        <!-- END EVEN WEEK -->
        </tbody>
    </table>

    <div class="week-types">
        <span class="week-type label label-week-type-odd">Odd week</span>
        <span class="week-type label label-inverse label-week-type-even">Even week</span>
    </div>

    <div class="form-actions">
        <button type="submit" class="btn btn-success user-planning-save" data-container='user_planning_<?php echo $user['id']; ?>'>Save</button>
        <span class="alert alert-error" style="display: none;">Error!</span>
    </div>
</div>
<?php endif; ?>