<?php if ( ! empty($this->user)): ?>
    <?php $user = $this->user; ?>
    <?php $userPlanning = $this->usersPlanning[$user['id']]; ?>

<div class="user-planning" id="user_planning_<?php echo $user['id']; ?>" data-user="<?php echo $user['id']; ?>" data-group="<?php echo $this->group['id']; ?>">
    <h2 class="user-planning-header">User: <?php echo $user['full_name']; ?> (<?php echo $user['email']; ?>)</h2>
    <table class="table table-bordered user-planning-weeks">
        <thead>
        <tr>
            <th class="span2">
                Monday
            </th>
            <th class="span2">
                Tuesday
            </th>
            <th class="span2">
                Wednesday
            </th>
            <th class="span2">
                Thursday
            </th>
            <th class="span2">
                Friday
            </th>
            <th class="span2">
                Saturday
            </th>
            <th class="span2">
                Sunday
            </th>
        </tr>
        </thead>
        <tbody>
        <!-- START ODD WEEK -->
    <?php foreach ($this->weekDays as $weekType => $dayData): ?>
        <tr style="background-color: #<?php echo $this->statusFreeDay['color_hex'] ?>;">
            <?php foreach ($this->weekDays[$weekType] as $key => $day): ?>
            <?php $data = '';
                if ( ! empty($userPlanning[$key])) {
                    $data = $userPlanning[$key];
                }?>
                <td class="week-day" style="background-color: #<?php echo @$userPlanning[$key]['color_hex'] ?>;">
                    <table class="table" style="margin-top: 5px; margin-bottom: 3px">
                        <tr>
                            <td width="20px">
                                <div class="" align="left">
                                    <div class="btn-group">
                                        <button class="btn dropdown-toggle" data-toggle="dropdown">
                                            <i class="icon-cog"></i>
                                        </button>
                                        <ul class="dropdown-menu" align="left">
                                            <li <?php if (empty($userPlanning[$key])) echo 'class="disabled"';?>>
                                                <a tabindex="-1"
                                                   href="<?php echo $this->url(array('controller' => 'group-settings', 'action' => 'set-work-plan-interval'), 'planner', true); ?>"
                                                   data-interval-id=""
                                                   data-current-interval-id="<?php if (isset($data['id'])) echo $data['id']; ?>"
                                                   data-user-id="<?php echo $user['id']; ?>"
                                                   data-group-id="<?php echo $this->group['id']; ?>"
                                                   data-week-type="<?php echo $weekType; ?>"
                                                   data-day-number="<?php echo $day['day_number']; ?>"
                                                   class="set-work-plan-interval no-action">
                                                    <span class="user-planning-color" style="background-color: #<?php echo $this->statusFreeDay['color_hex'] ?>;"></span>
                                                    <?php echo $this->statusFreeDay['description'] ?>
                                                </a>
                                            </li>
                                            <?php foreach( $this->workIntervals as $workInterval ) : ?>
                                                <li <?php if (isset($data['interval_id']) && $data['interval_id'] == $workInterval['id']) echo 'class="disabled"';?>>
                                                    <a tabindex="-1"
                                                        href="<?php echo $this->url(array('controller' => 'group-settings', 'action' => 'set-work-plan-interval'), 'planner', true); ?>"
                                                        data-interval-id="<?php echo $workInterval['id']; ?>"
                                                        data-user-id="<?php echo $user['id']; ?>"
                                                        data-group-id="<?php echo $this->group['id']; ?>"
                                                        data-week-type="<?php echo $weekType; ?>"
                                                        data-day-number="<?php echo $day['day_number']; ?>"
                                                        class="set-work-plan-interval no-action">
                                                        <span class="user-planning-color" style="background-color: #<?php echo $workInterval['color_hex'] ?>;"></span>
                                                        <?php echo $workInterval['format_time_start'] ?> <span>-</span>
                                                        <?php echo $workInterval['format_time_end']?>
                                                        <?php echo $workInterval['description']; ?>
                                                    </a>
                                                </li>
                                            <?php endforeach ?>
                                        </ul>

                                    </div>


                                </div>
                            </td>
                            <td text-align="left">Work
                                <?php if (!empty($userPlanning[$key])) {
                                    echo $workInterval['format_time_start'] . '-' . $workInterval['format_time_end'];
                                } ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <?php if (!empty($data)) : ?>
                                <div class="" align="left">
                                    <div class="btn-group">
                                        <button class="btn dropdown-toggle" data-toggle="dropdown">
                                            <i class="icon-cog"></i>
                                        </button>
                                        <ul class="dropdown-menu" align="left">
                                        <?php foreach( $this->pauseIntervals as $pauseInterval ) : ?>
                                            <li <?php
                                                $userPlannedPause = false;
                                                if (!empty($data['pause_id'][$pauseInterval['id']])) {
                                                    echo 'style="background-color:#d9d9d9"';
                                                    $userPlannedPause= true;
                                                }?> >
                                                <a tabindex="-1" href="
                                                    <?php echo $this->url(
                                                        array('controller' => 'group-settings',
                                                            'action' => 'set-pause-plan-interval'),
                                                        'planner', true);
                                                    ?>"
                                                    class="set-pause-plan-interval no-action"
                                                    data-planning-id="<?php echo $data['id']; ?>"
                                                    data-pause-id="<?php echo $pauseInterval['id']; ?>"
                                                    data-pause-delete="<?php echo $userPlannedPause; ?>"
                                                    >
                                                    <b> <?php if (!empty($userPlannedPause)) {
                                                            echo '-';
                                                        } else {
                                                            echo '+';
                                                        }?>
                                                    </b>
                                                    <?php echo $pauseInterval['format_time_start'] ?>-
                                                    <?php echo $pauseInterval['format_time_end']?>
                                                </a>
                                            </li>
                                        <?php endforeach ?>
                                        </ul>
                                    </div>
                                </div>
                            </td>
                            <td>
                                <table>
                                    <?php if (!empty($userPlanning[$key]['pause'])) :?>
                                    <?php foreach( $userPlanning[$key]['pause'] as $pausePlanInterval ) : ?>
                                        <tr>
                                            <td>
                                        Pause </td>
                                            <td><?php echo $pausePlanInterval['format_time_start'] . '-' . $pausePlanInterval['format_time_end'] ?>
                                            </td>
                                        </tr>
                                    <?php endforeach; ?>
                                    <?php else : ?>
                                        <tr>
                                            <td>
                                                Pause
                                            </td>
                                        </tr>
                                    <?php endif; ?>
                                </table
                                <?php endif; ?>
                            </td>
                        </tr>
                    </table>
                </td>
            <?php endforeach; ?>
        </tr>
    <?php endforeach; ?>
        <!-- END ODD WEEK -->
        </tbody>
    </table>

    <div class="week-types">
        <span class="week-type label label-week-type-odd">Top - Odd week</span>
        <span class="week-type label label-inverse label-week-type-even">Bottom - Even week</span>
    </div>

    <!--div class="form-actions">
        <button type="submit" class="btn btn-success user-planning-save" data-container='user_planning_<?php echo $user['id']; ?>'>Save</button>
        <span class="alert alert-error" style="display: none;">Error!</span>
    </div-->
</div>
<?php endif; ?>