<?php
/** @var $showDate DateTime */
$showDate  = $this->showDate;
$showMonth = $showDate->format('m');
$showYear  = $showDate->format('Y');

$start = clone $showDate;
$start->setDate($start->format('Y'), $start->format('m'), 1)->setTime(0, 0, 0); // set first day in month
$dayOffset = $start->format('w'); // 0 - sunday
if ( ! $dayOffset) {
    $dayOffset = 7;
}
$start->modify('-' . --$dayOffset . ' days');

$end = clone $showDate;
$end->setDate($end->format('Y'), $end->format('m'), $end->format('t'))->setTime(0, 0, 0); // set last day in month
$dayOffset = $end->format('w'); // 0 - sunday
if ( ! $dayOffset) {
    $dayOffset = 7;
}
$dayOffset = 7 - $dayOffset; // how much days left to the end of week
$end->modify('+' . $dayOffset . ' days');

$totalDays = $start->diff($end)->format('%a');
$endDate = clone $end;
$endDate->modify('+1 days');
$endDate = $endDate->format('Y-m-d');

$today = new DateTime();
$today->setTime(0, 0, 0);
$todayDate = $today->format('Y-m-d');
$todayTimestamp = $today->getTimestamp();

$selectedDates = implode(',', $this->selectedDates);
$oldSelectedDates = implode(',', $this->oldSelectedDates);
?>

<div
    class="module-calendar"
    data-selected-dates="<?php echo $selectedDates; ?>"
    data-old-selected-dates="<?php echo $oldSelectedDates; ?>"
    data-show-date="<?php echo $showDate->format('Y-m-d'); ?>"
    data-container-id="<?php echo $this->containerId; ?>"
    data-editable="<?php echo $this->editable; ?>"
>
    <div class="calendar-navigation">
        <div class="navigation-month pull-left input-prepend input-append">
            <div class="add-on calendar-change-date" data-change-type="month" data-change-direction="less">
                <span class="icon-arrow-left"></span>
            </div>
            <select name="show-month" class="span2 calendar-change-date-select calendar-select-month">
                <?php foreach ($this->months as $number => $name): ?>
                    <?php $selected = $number == $showMonth ? 'selected="selected"' : ''; ?>
                    <option value="<?php echo $number; ?>" <?php echo $selected; ?>><?php echo $name; ?></option>
                <?php endforeach; ?>
            </select>
            <div class="add-on calendar-change-date" data-change-type="month" data-change-direction="more">
                <span class="icon-arrow-right"></span>
            </div>
        </div>
        <div class="navigation-year pull-right input-prepend input-append">
            <div class="add-on calendar-change-date" data-change-type="year" data-change-direction="less">
                <span class="icon-arrow-left"></span>
            </div>
            <select name="show-year" class="span2 calendar-change-date-select calendar-select-year">
                <?php foreach ($this->years as $year): ?>
                    <?php $selected = $year == $showYear ? 'selected="selected"' : ''; ?>
                    <option value="<?php echo $year; ?>" <?php echo $selected; ?>><?php echo $year; ?></option>
                <?php endforeach; ?>
            </select>
            <div class="add-on calendar-change-date" data-change-type="year" data-change-direction="more">
                <span class="icon-arrow-right"></span>
            </div>
        </div>
    </div>

    <div class="days">
    <?php if ($totalDays > 0) : ?>
        <?php while($start->format('Y-m-d') != $endDate): ?>
            <?php
                $date      = $start->format('Y-m-d');
                $year      = $start->format('Y');
                $month     = $start->format('m');
                $day       = $start->format('d');
                $dayNumber = $start->format('w'); // 0 - sunday
                $timestamp = $start->getTimestamp();
                if ( ! $dayNumber) { $dayNumber = 7; }

                $css = array(
                    'isCurrentMonthClass' => $month == $showMonth ? 'current-month' : '',
                    'isWeekendClass'      => $dayNumber > 5 ? 'weekend' : '',
                    'isSelectedClass'     => in_array($date, (array)$this->selectedDates) ? 'selected' : '',
                    'isOldSelectedClass'  => in_array($date, (array)$this->oldSelectedDates) ? 'old-selected' : '',
                    'isToday'             => $date == $todayDate ? 'today' : '',
                    'isBlocked'          => $timestamp < $todayTimestamp ? 'blocked' : '',
                );
                $css = implode(' ', array_filter($css));
            ?>
            <?php if ($dayNumber == 1) : // monday ?>
                <?php
                $weeknumber = $start->format('W');
                ?>
                <div class="week-number">
                    <?php echo $weeknumber; ?>
                </div>
            <?php endif; ?>

            <div
                class="calendar-day-cell <?php echo $css; ?>"
                data-date="<?php echo $date; ?>"
                data-day="<?php echo $day; ?>">

                <?php echo $day; ?>
            </div>

            <?php $start->modify('+1 days'); ?>
        <?php endwhile; ?>
    <?php else: ?>
        Wrong data.
    <?php endif; ?>
    </div>

</div>
