<?php $this->headScript()->appendFile('/js/open-requests.js'); ?>

<div class="span12">
    <table class="table table-bordered open-request-group table-small-td">
        <thead>
        <tr>
            <th colspan="4">
                Groep Customer Service
            </th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td class="span3">
                Suzanne de Goede
            </td>
            <td class="span5">
                21.07.2012, 21.08.2012, 22.08.2012
            </td>
            <td class="span2 open-request-user-action">
                <button class="btn btn-small">Bekijk history</button>
            </td>
            <td class="span2 open-request-user-action">
                <button class="btn btn-small">Voeg toe</button>
            </td>
        </tr>
        <tr>
            <td>
                Harmen van der Meulen
            </td>
            <td>
                22.07.2012
            </td>
            <td class="open-request-user-action">
                <button class="btn btn-small">Bekijk history</button>
            </td>
            <td class="open-request-user-action">
                <button class="btn btn-small">Voeg toe</button>
            </td>
        </tr>
        <tr>
            <td>
                Erik de Wit
            </td>
            <td>

            </td>
            <td class="open-request-user-action">
                <button class="btn btn-small">Bekijk history</button>
            </td>
            <td class="open-request-user-action">
                <button class="btn btn-small">Voeg toe</button>
            </td>
        </tr>
        </tbody>
    </table>
    <table class="table table-bordered open-request-group table-small-td">
        <thead>
        <tr>
            <th colspan="4">
                Groep Marketing
            </th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td class="span3">
                Jantje Helder
            </td>
            <td class="span5">

            </td>
            <td class="span2 open-request-user-action">
                <button class="btn btn-small">Bekijk history</button>
            </td>
            <td class="span2 open-request-user-action">
                <button class="btn btn-small">Voeg toe</button>
            </td>
        </tr>
        <tr>
            <td>
                Erik Schmit
            </td>
            <td>

            </td>
            <td class="open-request-user-action">
                <button class="btn btn-small">Bekijk history</button>
            </td>
            <td class="open-request-user-action">
                <button class="btn btn-small">Voeg toe</button>
            </td>
        </tr>
        </tbody>
    </table>
</div>