<?php $this->headScript()->appendFile('/js/overview.js'); ?>

<div class="span12 group-overview-container">
    <div class="group-overview-header">
        <div class="pull-left">
            <a href="<?php echo $this->url(
                array(
                    'controller' => 'overview',
                    'action' => 'get-year-totals',
                    'year' => $this->year
                ), 'planner', true); ?>" class="show-tooltip no-action year-total" data-original-title="Show totals <?php echo $this->year; ?> year">
                <span class="param-name">Year totals</span>
            </a>
        </div>
        <div class="export-button pull-right">
            <a href="<?php echo $this->url(
                array(
                    'controller' => 'overview',
                    'action' => 'export',
                    'year' => $this->year,
                    'week' => $this->week,
                ), 'planner', true); ?>" class="show-tooltip" data-original-title="Export <?php echo $this->year; ?> year <?php echo $this->week; ?> week">
                <span class="param-name">Export</span>
            </a>
        </div>
    </div>

<?php foreach ($this->groups as $group): ?>
<?php $this->group = $group; ?>
<div
        class="row user_row width-full"
        id="<?php echo $this->group['id']; ?>"
        data-user-id="<?php echo $this->group['id']; ?>"
        >
    <?php
    $this->users = $this->group['users'];
    $nextWeekYear = $this->nextWeekYear;
    $prevWeekYear = $this->prevWeekYear;
    $currentWeekYear = $this->currentWeekYear;
    ?>
    <div class="user_row_container">
        <span class="span4 block-history">
            <a href="<?php echo $this->url(array('controller' => 'overview', 'action' => 'index', 'year' => $prevWeekYear['year'], 'week' => $prevWeekYear['week']), 'planner', true); ?>" rel="tooltip" class="bootstrab-tooltip get-week-details" title="<?php echo 'Year:' . $prevWeekYear['year'] . ' week:' . $prevWeekYear['week']; ?>">
                < Prev Week
            </a>
            <?php if ($currentWeekYear['week'] != $this->week): ?>
            <a href="<?php echo $this->url(array('controller' => 'overview', 'action' => 'index', 'year' => $currentWeekYear['year'], 'week' => $currentWeekYear['week']), 'planner', true); ?>" class="show-more-history"  title="<?php echo 'Year:' . $currentWeekYear['year'] . ' week:' . $currentWeekYear['week']; ?>">
                | Actual Week |
            </a>
            <a href="<?php echo $this->url(array('controller' => 'overview', 'action' => 'index', 'year' => $nextWeekYear['year'], 'week' => $nextWeekYear['week']), 'planner', true); ?>" rel="tooltip" class="bootstrab-tooltip get-week-details" title="<?php echo 'Year:' . $nextWeekYear['year'] . ' week:' . $nextWeekYear['week']; ?>">
                Next Week >
            </a>
            <?php endif; ?>
                <div class="history-container-scrollable">
                    <div class="history-container">
                        <?php
                        $this->historyBlockController = 'overview';
                        echo $this->render('_blocks/history.phtml'); ?>
                    </div>
                </div>
        </span>


        <span
                class="span10 block-week-details week-details main-data-container user-id-<?php echo $this->group['id']; ?> year-<?php echo $this->weekTasks['year']; ?> week-<?php echo $this->weekTasks['week']; ?>"
                data-year="<?php echo $this->weekTasks['year']; ?>"
                data-week="<?php echo $this->weekTasks['week']; ?>"
                data-userId="<?php echo $this->group['id']; ?>"
                >
         <?php echo $this->render('overview/_blocks/overview-user-row.phtml'); ?>
    </span>
    </div>
</div>
<?php endforeach; ?>

</div>

<!-- DEFAULT EDIT POPOVER -->
<div id="popover-edit-field-html" style="display: none;">
    <div class="popover-container" data-user="" data-group="" data-week="" data-year="" >
        <div class="input-append">
            <input type="text" name="" value="" class="input-edit-field for-focus">
            <button class="btn btn-success submit-popover-edit-field" type="button">Save</button>
        </div>
    </div>
</div>

<!-- Summarize year data popup -->
<div class="modal hide fade modal-year-total">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">X</button>
        <h3 class="header-year-total">Year Totals : <span class="tmpl-group-name"></span></h3>
    </div>
    <div class="modal-body-year-total">

    </div>
</div>