<?php $this->headScript()->appendFile('/js/overview.js'); ?>

<div class="span12 group-overview-container">
    <div class="group-overview-header">
        <div class="year-total pull-left">
            <a href="#" class="show-tooltip no-action" data-original-title="09:00 - 18:00">
                <span class="param-name">Year totals:</span>
                <span class="">2</span>
            </a>
        </div>
        <div class="export-button pull-right">
            <button class="btn btn-small">
                Export
            </button>
        </div>
    </div>

    <div class="group-history-block pull-left">
        <div class="div-row">
            <a href="#" class="no-action">
                More history
            </a>
        </div>
        <div class="group-history-table">
            <table class="table table-bordered table-small-td">
                <thead>
                <tr style="background-color: #F5F5DC;">
                    <th>Week 26</th>
                    <th>Week 27</th>
                    <th>Week 28</th>
                    <th>Week 29</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="group-history-block pull-left">
        <div class="div-row">&nbsp;</div>
        <div class="group-free-days-table">
            <table class="table table-bordered table-small-td">
                <thead>
                <tr style="background-color: #F5F5DC;">
                    <th>
                        Open
                        <a href="#" class="show-tooltip no-action" data-original-title="Openstaande saldo"><i class="icon-info-sign"></i></a>
                    </th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>
                        <span>2</span>
                        <a href="#" class="no-action pull-right">
                            <i class="icon-edit"></i>
                        </a>
                    </td>
                </tr>
                <tr>
                    <td>
                        <span>1</span>
                        <a href="#" class="no-action pull-right">
                            <i class="icon-edit"></i>
                        </a>
                    </td>
                </tr>
                <tr>
                    <td>
                        <span>3</span>
                        <a href="#" class="no-action pull-right">
                            <i class="icon-edit"></i>
                        </a>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="group-overview-block pull-left">
        <div class="div-row pull-right">
            <a href="#" class="no-action">
                Week 30
            </a>
        </div>
        <div class="group-overview-table">
            <table class="table table-bordered table-small-td">
                <thead>
                <tr style="background-color: #F5F5DC;">
                    <th class="group-user-name">Groep Customer Service</th>
                    <th class="group-user-worked">Gewerkte uren</th>
                    <th class="group-user-used-free-days">Vrije uren</th>
                    <th class="group-user-overtime">Overuren</th>
                    <th class="group-user-doctor-days">Ziekte/buitengew</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>Suzanne de Goede</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td>Harmen van der Meulen</td>
                    <td>
                        <span>71</span>
                        <a href="#" class="no-action pull-right"><i class="icon-edit"></i></a>
                    </td>
                    <td>
                        <span>14</span>
                        <a href="#" class="no-action pull-right"><i class="icon-edit"></i></a>
                    </td>
                    <td>
                        <span>0</span>
                        <a href="#" class="no-action pull-right"><i class="icon-edit"></i></a>
                    </td>
                    <td>
                        <span>3</span>
                        <a href="#" class="no-action pull-right"><i class="icon-edit"></i></a>
                    </td>
                </tr>
                <tr>
                    <td>Erik de Wit</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>















    <div class="group-history-block pull-left">
        <div class="group-history-table">
            <table class="table table-bordered table-small-td">
                <thead>
                <tr style="background-color: #FFFACD;">
                    <th>Week 26</th>
                    <th>Week 27</th>
                    <th>Week 28</th>
                    <th>Week 29</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="group-history-block pull-left">
        <div class="group-free-days-table">
            <table class="table table-bordered table-small-td">
                <thead>
                <tr style="background-color: #FFFACD;">
                    <th>
                        Open
                        <a href="#" class="show-tooltip no-action" data-original-title="Openstaande saldo"><i class="icon-info-sign"></i></a>
                    </th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>
                        <span>2</span>
                        <a href="#" class="no-action pull-right">
                            <i class="icon-edit"></i>
                        </a>
                    </td>
                </tr>
                <tr>
                    <td>
                        <span>1</span>
                        <a href="#" class="no-action pull-right">
                            <i class="icon-edit"></i>
                        </a>
                    </td>
                </tr>
                <tr>
                    <td>
                        <span>3</span>
                        <a href="#" class="no-action pull-right">
                            <i class="icon-edit"></i>
                        </a>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="group-overview-block pull-left">
        <div class="group-overview-table">
            <table class="table table-bordered table-small-td">
                <thead>
                <tr style="background-color: #FFFACD;">
                    <th class="group-user-name">Groep Marketing</th>
                    <th class="group-user-worked">Gewerkte uren</th>
                    <th class="group-user-used-free-days">Vrije uren</th>
                    <th class="group-user-overtime">Overuren</th>
                    <th class="group-user-doctor-days">Ziekte/buitengew</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>Suzanne de Goede</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td>Harmen van der Meulen</td>
                    <td>
                        <span>71</span>
                        <a href="#" class="no-action pull-right"><i class="icon-edit"></i></a>
                    </td>
                    <td>
                        <span>14</span>
                        <a href="#" class="no-action pull-right"><i class="icon-edit"></i></a>
                    </td>
                    <td>
                        <span>0</span>
                        <a href="#" class="no-action pull-right"><i class="icon-edit"></i></a>
                    </td>
                    <td>
                        <span>3</span>
                        <a href="#" class="no-action pull-right"><i class="icon-edit"></i></a>
                    </td>
                </tr>
                <tr>
                    <td>Erik de Wit</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>