<!-- this is management/auth/register -->
    <div class="row">
        <div class="span8">
            <?php echo $this->registerForm ?>
        </div>
        <div class="span8">
            <table class="table">
                    <thead>
                    <tr>
                        <th colspan="2">
                                User information
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="span2">
                            Email:
                        </td>
                        <td>
                            <?php echo $this->user['email']; ?>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            First name:
                        </td>
                        <td>
                            <?php echo $this->user['first_name']; ?>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Last name:
                        </td>
                        <td>
                            <?php echo $this->user['last_name']; ?>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Role:
                        </td>
                        <td>
                            <?php echo $this->user['role']; ?>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>