<?php $this->headScript()->appendFile('/js/user-settings.js'); ?>

<div class="span12">
    <table class="table table-bordered user-settings-table table-small-td">
        <thead>
        <tr>
            <th class="col-user-name">User</th>
            <th class="col-user-address">Address</th>
            <th class="col-user-phone">Phone</th>
            <th class="col-user-email">Mail</th>
            <th class="col-user-emergency-phone">Emergynumber</th>
            <th class="col-user-emergency-name">Emergyname</th>
            <th class="col-user-birthday">Birthdate</th>
            <th class="col-user-group">Group(s)</th>
            <th class="col-user-password">Password</th>
            <th class="col-user-work-hours">Hours <a href="#" class="show-tooltip no-action" data-original-title="(40h = 100%)"><i class="icon-info-sign"></i></a></th>
            <th class="col-user-work-time">Start/end <a href="#" class="show-tooltip no-action" data-original-title="Default start/end time"><i class="icon-info-sign"></i></a></th>
            <th class="col-user-owner">Eigen/Flex</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>
                Suzanne de Goede
            </td>
            <td>
                <div class="underflow-container">
                    <div class="underflow">
                        <a href="#" class="show-tooltip no-action" data-original-title="Nederland, SuperCity, str.Super, house 15">
                            Nederland, SuperCity,  str.Super, house 15
                        </a>
                    </div>
                </div>
            </td>
            <td>
                <div class="underflow-container">
                    <div class="underflow">
                        <a href="#" class="show-tooltip no-action" data-original-title="+380-63-123-45-67">
                            +380-63-123-45-67
                        </a>
                    </div>
                </div>
            </td>
            <td>
                <div class="underflow-container">
                    <div class="underflow">
                        <a href="#" class="show-tooltip no-action" data-original-title="harmen@futurumshop.nl">
                            harmen@futurumshop.nl
                        </a>
                    </div>
                </div>
            </td>
            <td>
                <div class="underflow-container">
                    <div class="underflow">
                        <a href="#" class="show-tooltip no-action" data-original-title="+380-63-123-45-67">
                            +380-63-123-45-67
                        </a>
                    </div>
                </div>
            </td>
            <td>
                <div class="underflow-container">
                    <div class="underflow">
                        <a href="#" class="show-tooltip no-action" data-original-title="Nederland, SuperCity, str.Super, house 15">
                            Nederland, SuperCity,  str.Super, house 15
                        </a>
                    </div>
                </div>
            </td>
            <td>
                <div class="underflow-container">
                    <div class="underflow">
                        <a href="#" class="show-tooltip no-action" data-original-title="01-02-2012">
                            01-02-2012
                        </a>
                    </div>
                </div>
            </td>
            <td>
                <div class="underflow-container">
                    <div class="underflow">
                        <a href="#" class="show-tooltip no-action" data-original-title="Marketing, Commercial, Business">
                            Marketing, Commercial, Business
                        </a>
                    </div>
                </div>
            </td>
            <td>
                <div class="underflow-container">
                    <div class="underflow">
                        <a href="#" class="show-tooltip no-action" data-original-title="Click here to change password">
                            **********
                        </a>
                    </div>
                </div>
            </td>
            <td>
                <div class="underflow-container">
                    <div class="underflow">
                        <a href="#" class="show-tooltip no-action" data-original-title="32">
                            32
                        </a>
                    </div>
                </div>
            </td>
            <td>
                <div class="underflow-container">
                    <div class="underflow">
                        <a href="#" class="show-tooltip no-action" data-original-title="09:00 - 18:00">
                            09:00 - 18:00
                        </a>
                    </div>
                </div>
            </td>
            <td>
                <div class="underflow-container">
                    <div class="underflow">
                        <a href="#" class="show-tooltip no-action" data-original-title="Change to own">
                            Eigen
                        </a>
                    </div>
                </div>
            </td>
        </tr>
        <tr>
            <td class="user-name-col">
                Harmen van der Meulen
            </td>
            <td></td> <td></td> <td></td>
            <td></td> <td></td> <td></td>
            <td></td> <td></td> <td></td>
            <td></td> <td></td>
        </tr>
        <tr>
            <td class="user-name-col">
                Erik de Wit
            </td>
            <td></td> <td></td> <td></td>
            <td></td> <td></td> <td></td>
            <td></td> <td></td> <td></td>
            <td></td> <td></td>
        </tr>
        <tr>
            <td class="user-name-col">
                Jantje Helder
            </td>
            <td></td> <td></td> <td></td>
            <td></td> <td></td> <td></td>
            <td></td> <td></td> <td></td>
            <td></td> <td></td>
        </tr>
        <tr>
            <td class="user-name-col">
                Erik Schmit
            </td>
            <td></td> <td></td> <td></td>
            <td></td> <td></td> <td></td>
            <td></td> <td></td> <td></td>
            <td></td> <td></td>
        </tr>
        </tbody>
    </table>
</div>