<?php $this->headScript()->appendFile('/js/user-settings.js'); ?>

<div class="span12">
    <table class="table table-bordered table-hover user-settings-table table-small-td">
        <thead>
        <tr>
            <th class="col-user-name">User</th>
            <th class="col-user-address">Address</th>
            <th class="col-user-phone">Phone</th>
            <th class="col-user-email">Mail</th>
            <th class="col-user-emergency-phone">Emergynumber</th>
            <th class="col-user-emergency-name">Emergyname</th>
            <th class="col-user-birthday">Birthdate</th>
            <th class="col-user-group">Group(s)</th>
            <th class="col-user-password">Password</th>
            <th class="col-user-work-hours">Hours <a href="#" class="show-tooltip no-action" data-original-title="(40h = 100%)" data-placement="top"><i class="icon-info-sign"></i></a></th>
            <th class="col-user-work-time">Start/end <a href="#" class="show-tooltip no-action" data-original-title="Default start/end time" data-placement="top"><i class="icon-info-sign"></i></a></th>
            <th class="col-user-owner">Eigen/Flex</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($this->users as $user): ?>

        <?php
        $groups = array();
        $groupRoles = '';
        $adminGroups = array_flip($user['admin_groups']);
        foreach ($user['groups'] as $group) {
            $admin = isset($adminGroups[$group['id']]) ? 1 : 0;
            if ($admin) {
                $groups[] = '<strong>' . $group['group_name'] . '</strong>';
            } else {
                $groups[] = $group['group_name'];
            }
            $groupRoles .= $group['id'] . ':' . $admin . ';';
        }
        $groups = implode(', ', $groups);
        $groupRoles = rtrim($groupRoles, ';');
        ?>

        <tr data-user="<?php echo $user['id']; ?>">
            <td class="show-tooltip" data-original-title="<?php echo $user['full_name']; ?>" data-placement="top">
                <div class="underflow-container editable" data-field-title="Full name" data-field-name="full_name" data-field-value="<?php echo $user['full_name']; ?>" data-placement="right">
                    <div class="underflow">
                        <?php echo $user['full_name']; ?>
                    </div>
                </div>
            </td>
            <td class="show-tooltip" data-original-title="<?php echo $user['address']; ?>" data-placement="top">
                <?php if ($this->me['role'] == Application_Model_Auth::ROLE_SUPER_ADMIN): ?>
                    <i class="icon-cog change-role-icon show-tooltip" data-original-title="Current role: '<?php echo $this->roles[$user['role']]; ?>'</br>Click to change" data-placement="top""></i>
                <?php endif; ?>
                <div class="underflow-container editable" data-field-title="Address" data-field-name="address" data-field-value="<?php echo $user['address']; ?>">
                    <div class="underflow">
                        <?php echo $user['address']; ?>
                    </div>
                </div>
            </td>
            <td class="show-tooltip" data-original-title="<?php echo $user['phone']; ?>" data-placement="top">
                <div class="underflow-container editable" data-field-title="Phone" data-field-name="phone" data-field-value="<?php echo $user['phone']; ?>">
                    <div class="underflow">
                        <?php echo $user['phone']; ?>
                    </div>
                </div>
            </td>
            <td class="show-tooltip" data-original-title="<?php echo $user['email']; ?>" data-placement="top">
                <div class="underflow-container editable" data-field-title="Mail" data-field-name="email" data-field-value="<?php echo $user['email']; ?>">
                    <div class="underflow">
                        <?php echo $user['email']; ?>
                    </div>
                </div>
            </td>
            <td class="show-tooltip" data-original-title="<?php echo $user['emergency_phone']; ?>" data-placement="top">
                <div class="underflow-container editable" data-field-title="Emergynumber" data-field-name="emergency_phone" data-field-value="<?php echo $user['emergency_phone']; ?>">
                    <div class="underflow">
                        <?php echo $user['emergency_phone']; ?>
                    </div>
                </div>
            </td>
            <td class="show-tooltip" data-original-title="<?php echo $user['emergency_full_name']; ?>" data-placement="top">
                <div class="underflow-container editable" data-field-title="Emergyname" data-field-name="emergency_full_name" data-field-value="<?php echo $user['emergency_full_name']; ?>">
                    <div class="underflow">
                        <?php echo $user['emergency_full_name']; ?>
                    </div>
                </div>
            </td>
            <td class="show-tooltip" data-original-title="<?php echo $user['birthday']; ?>" data-placement="top">
                <div class="underflow-container editable editable-birthday" data-field-title="Birthdate" data-field-name="birthday" data-field-value="<?php echo $user['birthday']; ?>">
                    <div class="underflow">
                        <?php echo $user['birthday']; ?>
                    </div>
                </div>
            </td>
            <td class="show-tooltip" data-original-title="<?php echo $groups; ?>" data-placement="top">
                <div class="underflow-container editable-popup editable-groups" data-field-title="Groups for user: <?php echo $user['full_name']; ?>" data-field-name="groups" data-field-value="<?php echo $groupRoles; ?>">
                    <div class="underflow">
                        <?php echo $groups; ?>
                    </div>
                </div>
            </td>
            <td class="show-tooltip" data-original-title="Click here to change password" data-placement="top">
                <div class="underflow-container editable">
                    <div class="underflow">
                        **********
                    </div>
                </div>
            </td>
            <td class="show-tooltip" data-original-title="32<?php // echo $user['hours']; ?>" data-placement="top">
                <div class="underflow-container editable">
                    <div class="underflow">
                        32<?php // echo $user['hours']; ?>
                    </div>
                </div>
            </td>
            <td class="show-tooltip" data-original-title="09:00 - 18:00<?php // echo $user['time_work']['start'] . ' - ' . $user['time_work']['end']; ?>" data-placement="top">
                <div class="underflow-container editable">
                    <div class="underflow">
                        09:00 - 18:00<?php // echo $user['time_work']['start'] . ' - ' . $user['time_work']['end']; ?>
                    </div>
                </div>
            </td>
            <td class="show-tooltip" data-original-title="<?php echo $user['owner']; ?>" data-placement="top">
                <div class="underflow-container editable" data-field-title="Owner" data-field-name="owner" data-field-value="<?php echo $user['owner']; ?>">
                    <div class="underflow">
                        <?php echo $user['owner']; ?>
                    </div>
                </div>
            </td>
        </tr>

        <?php endforeach; ?>

        </tbody>
    </table>
</div>

<!-- DEFAULT EDIT POPOVER -->
<div id="popover-edit-field-html" style="display: none;">
    <div class="popover-container" data-user="">
        <div class="input-append">
            <input type="text" name="" value="" class="input-edit-field for-focus">
            <button class="btn btn-success submit-popover-edit-field" type="button">Save</button>
        </div>
    </div>
</div>

<!-- BIRTHDAY EDIT POPOVER -->
<div id="popover-edit-field-birthday-html" style="display: none;">
    <div class="popover-container" data-user="">
        &nbsp;Day: <input type="text" name="" value="" class="input-edit-field input-date-day for-focus" placeholder="DD" maxlength="2">
        &nbsp;Month: <input type="text" name="" value="" class="input-edit-field input-date-month" placeholder="MM" maxlength="2">
        &nbsp;Year: <input type="text" name="" value="" class="input-edit-field input-date-year" placeholder="YYYY" maxlength="4">
        <button class="btn btn-success submit-popover-edit-field" type="button">Save</button>
        <div class="small-tip">allowed values from 1940-01-01 to 2010-01-01</div>
    </div>
</div>

<!-- GROUPS EDIT POPUP -->
<div id="popup-edit-form-groups-html" style="display: none;">
    <div class="edit-form-groups popup-container" data-user="">
        <table class="table">
            <thead>
                <tr>
                    <th class="span6">
                        Group name
                    </th>
                    <th>
                        Actions
                    </th>
                </tr>
            </thead>
            <tbody>
        <?php foreach ($this->groups as $group): ?>
            <?php $id = $group['id']; ?>
                <tr style="background-color: #<?php echo $group['color']; ?>;">
                    <td>
                        <input type="checkbox" name="group-id-<?php echo $id; ?>" class="group-checkbox group-id group-id-<?php echo $group['id']; ?>" data-toggle="button" data-group-id="<?php echo $group['id']; ?>"">
                        <?php echo $group['group_name']; ?>
                    </td>
                    <td>
                        <input type="checkbox" name="group-id-<?php echo $id; ?>" class="group-checkbox group-admin-<?php echo $group['id']; ?>" data-toggle="button" data-group-id="<?php echo $group['id']; ?>"">
                    </td>
                </tr>
        <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<div class="modal hide span12 popup" id="edit-form-modal">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">X</button>
        <h3></h3>
    </div>
    <div class="modal-body">
    </div>
    <div class="modal-footer">
        <button class="btn btn-success submit-edit-form" data-status='approved'>Save</button>
    </div>
</div>