<?php
$this->users = $this->group['users'];
?>
<?php if (empty($this->users)): ?>
<td colspan="7" class="user-not-found">
    No users in this group
</td>
    <?php else: ?>
    <tr>
    <td  class="group-user-name" style="background-color: #<?php echo $this->group['color'];?>"><b><?php echo $this->group['group_name']; ?></b></td>
    <td colspan="7" style="background-color:#f9f9f9">

    </td>
    </tr>
    <?php foreach ($this->users as $user): ?>
        <?php $this->user = $user; ?>
        <?php echo $this->render('planning/_blocks/week_user_plan.phtml'); ?>
    <?php endforeach; ?>
    <?php endif; ?>
