<?php echo $this->doctype() ?>
<html>
<head>
    <?php $this->headLink()
        ->appendStylesheet('/css/bootstrap.css')
        ->appendStylesheet('/css/styles.css')
    ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headTitle() ?>

    <?php $this->headScript()->prependFile('/js/global.js'); ?>
    <?php
    $this->headScript()
        ->prependFile('/js/bootstrap/js/bootstrap.js')
        ->prependFile('/js/jquery/jquery/jquery.form.js')
        ->prependFile('/js/jquery/jquery-1.7.2.min.js')
?>
</head>
<body>
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <!-- TOP PANEL -->

            <a class="brand" href="<?php echo $this->url(array(), null, true) ?>">Futurumshop: Planner</a>

            <!-- TOP PANEL -->
        </div>
    </div>
</div>
<div class="container" id="container">
    <?php echo $this->layout()->content ?>
</div>
<?php echo $this->headScript(); ?>
</body>
</html>