<?php echo $this->doctype() ?>
<html>
<head>
    <?php $this->headLink()
        ->appendStylesheet('/css/bootstrap.css')
        ->appendStylesheet('/css/styles.css')
    ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headTitle() ?>

    <?php $this->headScript()->prependFile('/js/global.js'); ?>
    <?php
    if ( ! empty($this->me['role']) && $this->me['role'] === Application_Model_Auth::ROLE_ADMIN)
       //TODO insert additional scripts for admin
    ?>
    <?php $this->headScript()->prependFile('/js/modules/planner/planner.js'); ?>
    <?php
    $this->headScript()
        ->prependFile('/js/bootstrap/js/bootstrap.js')
        ->prependFile('/js/jquery/jquery/jquery.form.js')
        ->prependFile('/js/jquery/jquery-1.7.2.min.js')
?>
</head>
<body>
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <!-- TOP PANEL -->

            <a class="brand" href="<?php echo $this->url(array(), null, true) ?>">Futurumshop: Planner</a>

            <?php if ( ! empty($this->me)): ?>
            <ul class="nav pull-right">
                <li>
                    <?php $title = $this->me['role'] . ': ' . $this->me['first_name'] . ' ' . $this->me['last_name'] . ' (' . $this->me['email'] . ')'; ?>
                    <a href="<?php echo $this->url(array('controller' => 'auth', 'action' => 'logout'), 'management_full', true); ?>" id='logout-link' title="<?php echo $title; ?>">Logout</a>
                </li>
            </ul>
            <?php endif; ?>

            <!-- TOP PANEL -->
        </div>
    </div>
</div>
<div class="container" id="container" data-project-id="<?php echo @$this->projectId; ?>">
    <?php echo $this->layout()->content ?>

</div>
<?php echo $this->headScript(); ?>
</body>
</html>