<?php echo $this->doctype() ?>
<html>
<head>
    <?php $this->headLink()
        ->appendStylesheet('/css/bootstrap.css')
        ->appendStylesheet('/css/styles.css')
    ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headTitle() ?>

    <?php
    $this->headScript()
        ->prependFile('/js/global.js')
        ->prependFile('/js/bootstrap.js')
        ->prependFile('/js/jquery.form.js')
        ->prependFile('/js/jquery-1.8.2.min.js')
?>
</head>
<body>
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <!-- TOP PANEL -->

            <a class="brand" href="<?php echo $this->url(array(), null, true) ?>">Futurumshop: Planner</a>
            <?php if ($this->me['role'] >= Application_Model_Auth::ROLE_USER): ?>
            <ul class="nav">
                <li <?php if ($this->activeMenu == 'checking'): ?>class="active"<?php endif; ?>>
                    <a href="<?php echo $this->url(array('controller' => 'checking'), null, true) ?>">
                        Check IN/OUT
                    </a>
                </li>
                <li <?php if ($this->activeMenu == 'planning'): ?>class="active"<?php endif; ?>>
                    <a href="<?php echo $this->url(array('controller' => 'planning'), 'planner', true) ?>">
                        Planning
                    </a>
                </li>
                <li <?php if ($this->activeMenu == 'requests'): ?>class="active"<?php endif; ?>>
                    <a href="<?php echo $this->url(array('controller' => 'requests'), 'planner', true) ?>">
                        Vrij aanvraag
                    </a>
                </li>
                <?php if ($this->me['role'] >= Application_Model_Auth::ROLE_GROUP_ADMIN): ?>
                <li <?php if ($this->activeMenu == 'open-requests'): ?>class="active"<?php endif; ?>>
                    <a href="<?php echo $this->url(array('controller' => 'open-requests'), 'planner', true) ?>">
                        Accordering
                    </a>
                </li>
                <?php endif; ?>
                <?php if ($this->me['role'] >= Application_Model_Auth::ROLE_ADMIN): ?>
                <li <?php if ($this->activeMenu == 'group-settings'): ?>class="active"<?php endif; ?>>
                    <a href="<?php echo $this->url(array('controller' => 'group-settings'), 'planner', true) ?>">
                        Settings groepen
                    </a>
                </li>
                <li <?php if ($this->activeMenu == 'user-settings'): ?>class="active"<?php endif; ?>>
                    <a href="<?php echo $this->url(array('controller' => 'user-settings'), 'planner', true) ?>">
                        Settings users
                    </a>
                </li>
                <li <?php if ($this->activeMenu == 'overview'): ?>class="active"<?php endif; ?>>
                    <a href="<?php echo $this->url(array('controller' => 'overview'), 'planner', true) ?>">
                        Overzicht
                    </a>
                </li>
                <li <?php if ($this->activeMenu == 'alerts'): ?>class="active"<?php endif; ?>>
                    <a href="<?php echo $this->url(array('controller' => 'alerts'), 'planner', true) ?>">
                        Alerts
                    </a>
                </li>
                <?php endif; ?>
                <li class="divider-vertical"></li>
                <li>
                    <?php
                    $title = Application_Model_Auth::getRole(true) . ': ' . $this->me['full_name'] . '
                    (' . $this->me['email'] . ')';
                    ?>
                    <a id="logout-link" href="<?php echo $this->url(array(), 'logout', true) ?>" title="<?php echo $title; ?>">
                        Logout
                    </a>
                </li>
            </ul>
            <?php endif; ?>

            <!-- TOP PANEL -->
        </div>
    </div>
</div>
<div class="container" id="container">
    <?php echo $this->layout()->content ?>
</div>
<?php echo $this->headScript(); ?>
</body>
</html>
