<?php $this->headScript()->appendFile('/js/planning.js'); ?>
<?php $this->headScript()->appendFile('/js/bootstrap-timepicker.js'); ?>
<?php $this->headLink()->appendStylesheet('/css/timepicker.css')
?>
<?php if (empty($this->groups)): ?>
<h2>No groups and users</h2>
<?php else: ?>


<?php foreach ($this->groups as $group): ?>
    <?php $this->group = $group; ?>
    <?php echo $this->render('planning/_blocks/group_row.phtml'); ?>
    <?php endforeach; ?>

<?php endif; ?>
<div class="div-row">&nbsp;</div>
<div class="div-row">&nbsp;</div>
<div class="div-row">&nbsp;</div>
<div class="div-row">&nbsp;</div>
<div class="div-row">&nbsp;</div>

<div class="modal hide fade modal-edit-day">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">X</button>
        <h3 class="header-edit-day">Edit day : <span class="tmpl-group-name"></span></h3>
    </div>
    <div class="modal-body">


    </div>

    <div class="modal-footer">
        <div class="user-checking-container"></div>
        <div class="pull-left">
            Work hours plan: <span class="work-hours-plan"><?php echo $this->workHoursPlan; ?></span><br />
            Work hours done: <span class="work-hours-done"><?php echo $this->workHoursDone; ?></span><br />
            Work hours overtime: <span class="work-hours-overtime"><?php echo $this->workHoursOvertime; ?></span><br />
        </div>
        <div class="pull-right save-checkin-data-button">
            <button type="button" class="btn btn-primary button-submit" id="form-edit-day" data-form="form-edit-day">Save</button>
        </div>
    </div>
</div>