<?php $this->headScript()->appendFile($this->baseUrl() . '/js/alerts.js'); ?>

<div class="span12 alerts-container">
    <div class="alert-1-header">
        <span class="alert-name">Alert 1 : no checkin without reason</span>
    </div>

    <div class="alert-1-block pull-left">
        <div class="div-row">
            <a href="#" class="no-action">
                More history
            </a>
        </div>
        <div class="alert-1-history-table">
            <table class="table table-bordered table-small-td">
                <thead>
                <tr style="background-color: #F5F5DC;">
                    <th>Week 26</th>
                    <th>Week 27</th>
                    <th>Week 28</th>
                    <th>Week 29</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="alert-1-block pull-left">
        <div class="div-row">
            <div class="underflow-container">
                <div class="underflow">
                    Previous years history total
                </div>
            </div>
        </div>
        <div class="alert-1-year-table">
            <table class="table table-bordered table-small-td">
                <thead>
                <tr style="background-color: #F5F5DC;">
                    <th>
                        Year total
                    </th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>
                        <span>2</span>
                    </td>
                </tr>
                <tr>
                    <td>
                        <span>1</span>
                    </td>
                </tr>
                <tr>
                    <td>
                        <span>3</span>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="alert-1-block pull-left">
        <div class="div-row pull-right">&nbsp;</div>
        <div class="alert-1-group-table">
            <table class="table table-bordered table-small-td">
                <thead>
                <tr style="background-color: #F5F5DC;">
                    <th class="alert-1-user-name">Groep Customer Service</th>
                    <th class="alert-1-user-worked">Not there</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>Suzanne de Goede</td>
                    <td>
                        <span>0</span>
                        <a href="#" class="no-action pull-right show-tooltip" data-original-title="Edit into reason"><i class="icon-edit"></i></a>
                    </td>
                </tr>
                <tr>
                    <td>Harmen van der Meulen</td>
                    <td>
                        <span>1</span>
                        <a href="#" class="no-action pull-right show-tooltip" data-original-title="Edit into reason"><i class="icon-edit"></i></a>
                    </td>
                </tr>
                <tr>
                    <td>Erik de Wit</td>
                    <td>
                        <span>0</span>
                        <a href="#" class="no-action pull-right show-tooltip" data-original-title="Edit into reason"><i class="icon-edit"></i></a>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>















    <div class="alert-1-block pull-left">
        <div class="alert-1-history-table">
            <table class="table table-bordered table-small-td">
                <thead>
                <tr style="background-color: #F5F5DC;">
                    <th>Week 26</th>
                    <th>Week 27</th>
                    <th>Week 28</th>
                    <th>Week 29</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="alert-1-block pull-left">
        <div class="alert-1-year-table">
            <table class="table table-bordered table-small-td">
                <thead>
                <tr style="background-color: #F5F5DC;">
                    <th>
                        Year total
                    </th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>
                        <span>2</span>
                    </td>
                </tr>
                <tr>
                    <td>
                        <span>1</span>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="alert-1-block pull-left">
        <div class="alert-1-group-table">
            <table class="table table-bordered table-small-td">
                <thead>
                <tr style="background-color: #F5F5DC;">
                    <th class="alert-1-user-name">Groep Customer Service</th>
                    <th class="alert-1-user-worked">Not there</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>Jantje Helder</td>
                    <td>
                        <span>0</span>
                        <a href="#" class="no-action pull-right show-tooltip" data-original-title="Edit into reason"><i class="icon-edit"></i></a>
                    </td>
                </tr>
                <tr>
                    <td>Erik Schmit</td>
                    <td>
                        <span>1</span>
                        <a href="#" class="no-action pull-right show-tooltip" data-original-title="Edit into reason"><i class="icon-edit"></i></a>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
