<?php $this->headScript()->appendFile('/js/requests.js'); ?>
<?php /********** INCLUDE CALENDAR MODULE *****************/ ?>
<?php $this->headScript()->appendFile('/js/calendar.js'); ?>
<?php $this->headLink()->appendStylesheet('/css/calendar.css'); ?>

<?php
$openRequestDates     = array();
$approvedRequestDates = array();
$rejectedRequestDates = array();
$usedRequestDates     = array();
foreach ($this->userRequests[Application_Model_Db_User_Requests::USER_REQUEST_STATUS_OPEN] as $request) {
    $openRequestDates[] = $request['request_date'];
};
foreach ($this->userRequests[Application_Model_Db_User_Requests::USER_REQUEST_STATUS_APPROVED] as $request) {
    try {
        $requestDate = new My_DateTime($request['request_date']);
    } catch (Exception $e) {continue;}
    $approvedRequestDates[] = $request['request_date'];
    if ($requestDate->getTimestamp() < time()) { // today is used too . Bug only in 00:00:00 .
        $usedRequestDates[] = $request['request_date'];
    }
};
foreach ($this->userRequests[Application_Model_Db_User_Requests::USER_REQUEST_STATUS_REJECTED] as $request) {
    $rejectedRequestDates[] = $request['request_date'];
};
?>

<div class="span4">
    <?php echo $this->me['full_name']; ?>
</div>
<div class="span4">
    <span class="param-name">Gebruikt saldo:</span> <span class="use-free-hours"><?php echo $this->me['parameters']['used_free_hours']; ?></span>
</div>
<div class="span4">
    <span class="param-name">Openstaand saldo:</span> <span class="allowed-free-hours"><?php echo $this->me['parameters']['allowed_free_hours']; ?></span>
</div>

<div class="span12" id="request-calendar-container">
    <div class="span12">
        <div
            class="module-calendar"
            data-old-selected-dates="<?php echo implode(',', $openRequestDates); ?>"
            data-selected-dates=""
            data-blocked-dates="<?php echo implode(',', $this->blocked); ?>"
            data-container-id="request-calendar-container"
            data-editable="1"
        ></div>
    </div>
    <div class="span12">
        <span class="param-name">Geselecteerd is:</span> <span class="request-calendar-selected-days"></span>
    </div>
    <div class="span6">
        <input class="btn btn-success pull-right" type="button" id="save-request" value="Submit">
    </div>
</div>

<div class="span12">
    <table class="table requests-table table-hover">
        <tbody>
        <tr>
            <td class="span3">
                Openstaande aanvragen:
            </td>
            <td>
                <?php echo implode(', ', $openRequestDates); ?>
            </td>
            <td>
                <button class="btn show-in-calendar pull-right"
                    data-old-selected-dates="<?php echo implode(',', $openRequestDates); ?>"
                    data-show-date="<?php echo end($openRequestDates); ?>"
                ><span class="icon-eye-open"></span></button>
            </td>
        </tr>
        <tr>
            <td class="span3">
                Geaccordeerde aanvragen:
            </td>
            <td>
                <?php echo implode(', ', $approvedRequestDates); ?>
            </td>
            <td>
                <button class="btn show-in-calendar pull-right"
                    data-old-selected-dates="<?php echo implode(',', $approvedRequestDates); ?>"
                    data-show-date="<?php echo end($approvedRequestDates); ?>"
                ><span class="icon-eye-open"></span></button>
            </td>
        </tr>
        <tr>
            <td class="span3">
                Afgewezen dagen:
            </td>
            <td>
                <?php echo implode(', ', $rejectedRequestDates); ?>
            </td>
            <td>
                <button class="btn show-in-calendar pull-right"
                    data-selected-dates="<?php echo implode(',', $rejectedRequestDates); ?>"
                    data-show-date="<?php echo end($rejectedRequestDates); ?>"
                ><span class="icon-eye-open"></span></button>
            </td>
        </tr>
        <tr>
            <td class="span3">
                Historische dagen dit jaar:
            </td>
            <td>
                <?php echo implode(', ', $usedRequestDates); ?>
            </td>
            <td>
                <button class="btn show-in-calendar pull-right"
                    data-selected-dates="<?php echo implode(',', $usedRequestDates); ?>"
                    data-show-date="<?php echo end($usedRequestDates); ?>"
                ><span class="icon-eye-open"></span></button>
            </td>
        </tr>
        </tbody>
    </table>
</div>