<?php $this->headScript()->appendFile($this->baseUrl() . '/js/requests.js'); ?>
<?php /********** INCLUDE CALENDAR MODULE *****************/ ?>
<?php $this->headScript()->appendFile($this->baseUrl() . '/js/calendar.js'); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl() . '/css/calendar.css'); ?>

<?php
$openRequestDates     = array();
$approvedRequestDates = array();
$rejectedRequestDates = array();
$usedRequestDates     = array();
$usedRequestDatesComments = array();
foreach ($this->userRequests[Application_Model_Db_User_Requests::USER_REQUEST_STATUS_OPEN] as $request) {
    $openRequestDates[] = $request['request_date'];
};
foreach ($this->userRequests[Application_Model_Db_User_Requests::USER_REQUEST_STATUS_APPROVED] as $request) {
    try {
        $requestDate = new My_DateTime($request['request_date']);
    } catch (Exception $e) {continue;}
    $approvedRequestDates[] = $request['request_date'];
    if ($requestDate->getTimestamp() < time()) { // today is used too . Bug only in 00:00:00 .
        $usedRequestDates[] = $request['request_date'];
        $usedRequestDatesComments[$request['request_date']] = $request['comment'];
    }
};
foreach ($this->userRequests[Application_Model_Db_User_Requests::USER_REQUEST_STATUS_REJECTED] as $request) {
    $rejectedRequestDates[] = $request['request_date'];
};

$holidays = array();
$holidaysTitles = array();
foreach ($this->regularHolidays as $holiday) {
    $holidays[] = $holiday['holiday_date'];
    $holiday['holiday_name'] = trim($holiday['holiday_name']);
    if ( ! empty($holiday['holiday_name'])) {
        $holidaysTitles[$holiday['holiday_date']] = $holiday['holiday_name'];
    }
}
$holidays = json_encode($holidays);
$holidaysTitles = json_encode($holidaysTitles);
?>
<script language="JavaScript">
    var calendarHolidays = <?php echo ($holidays ? $holidays : '[]'); ?>;
    var calendarHolidaysTitles = <?php echo ($holidaysTitles ? $holidaysTitles : '{}'); ?>;
</script>

<div class="span4">
    <?php echo $this->me['full_name']; ?>
</div>
<div class="span4">
    <span class="param-name">Gebruikt saldo:</span> <span class="use-free-hours"><?php echo $this->preUsedFreeHours; ?></span>
</div>
<div class="span4">
    <span class="param-name">Openstaand saldo:</span> <span class="allowed-free-hours"><?php echo $this->preAllowedFreeHours; ?></span>
</div>

<div class="span12" id="request-calendar-container">
    <div class="span12">
        <div
            class="module-calendar"
            data-old-selected-dates="<?php echo implode(',', $openRequestDates); ?>"
            data-selected-dates=""
            data-blocked-dates="<?php echo implode(',', $this->blocked); ?>"
            data-container-id="request-calendar-container"
            data-editable="1"
        ></div>
    </div>
    <div class="span12">
        <span class="param-name">Geselecteerd is:</span> <span class="request-calendar-selected-days"></span>
    </div>
    <div class="span6">
        <input class="btn btn-success pull-right" type="button" id="save-request" value="Submit">
    </div>
</div>

<div class="span12">
    <table class="table requests-table table-hover">
        <tbody>
        <tr>
            <td class="span3">
                Openstaande aanvragen:
            </td>
            <td>
                <?php foreach ($this->userRequests[Application_Model_Db_User_Requests::USER_REQUEST_STATUS_OPEN] as $request) : ?>
                    <?php if ( ! empty($request['comment'])) : ?>
                        <div class="show-tooltip editable request-show-comment pull-left" data-original-title="<?php echo $request['comment']; ?>">
                            <?php echo $request['request_date']; ?>,
                        </div>
                        <?php else : ?>
                        <div class="pull-left">
                            <?php echo $request['request_date']; ?>,
                        </div>
                    <?php endif; ?>
                <?php endforeach; ?>
            </td>
            <td>
                <button class="btn show-in-calendar pull-right"
                    data-old-selected-dates="<?php echo implode(',', $openRequestDates); ?>"
                    data-show-date="<?php echo end($openRequestDates); ?>"
                ><span class="icon-eye-open"></span></button>
            </td>
        </tr>
        <tr>
            <td class="span3">
                Geaccordeerde aanvragen:
            </td>
            <td>
                <?php foreach ($this->userRequests[Application_Model_Db_User_Requests::USER_REQUEST_STATUS_APPROVED] as $request) : ?>
                    <?php if ( ! empty($request['comment'])) : ?>
                        <div class="show-tooltip editable request-show-comment pull-left" data-original-title="<?php echo $request['comment']; ?>">
                            <?php echo $request['request_date']; ?>,
                        </div>
                        <?php else : ?>
                        <div class="pull-left">
                            <?php echo $request['request_date']; ?>,
                        </div>
                    <?php endif; ?>
                <?php endforeach; ?>
            </td>
            <td>
                <button class="btn show-in-calendar pull-right"
                    data-old-selected-dates="<?php echo implode(',', $approvedRequestDates); ?>"
                    data-show-date="<?php echo end($approvedRequestDates); ?>"
                ><span class="icon-eye-open"></span></button>
            </td>
        </tr>
        <tr>
            <td class="span3">
                Afgewezen dagen:
            </td>
            <td>
                <?php foreach ($this->userRequests[Application_Model_Db_User_Requests::USER_REQUEST_STATUS_REJECTED] as $request) : ?>
                    <?php if ( ! empty($request['comment'])) : ?>
                        <div class="show-tooltip editable request-show-comment pull-left" data-original-title="<?php echo $request['comment']; ?>">
                            <?php echo $request['request_date']; ?>,
                        </div>
                    <?php else : ?>
                        <div class="pull-left">
                            <?php echo $request['request_date']; ?>,
                        </div>
                    <?php endif; ?>
                <?php endforeach; ?>
            </td>
            <td>
                <button class="btn show-in-calendar pull-right"
                    data-selected-dates="<?php echo implode(',', $rejectedRequestDates); ?>"
                    data-show-date="<?php echo end($rejectedRequestDates); ?>"
                ><span class="icon-eye-open"></span></button>
            </td>
        </tr>
        <tr>
            <td class="span3">
                Historische dagen dit jaar:
            </td>
            <td>
                <?php foreach ($usedRequestDates as $request) : ?>
                    <?php $comment = $usedRequestDatesComments[$request] || ''; ?>
                    <?php if ( ! empty($comment)) : ?>
                        <div class="show-tooltip editable request-show-comment pull-left" data-original-title="<?php echo $comment; ?>">
                            <?php echo $request; ?>,
                        </div>
                        <?php else : ?>
                        <div class="pull-left">
                            <?php echo $request; ?>,
                        </div>
                    <?php endif; ?>
                <?php endforeach; ?>
            </td>
            <td>
                <button class="btn show-in-calendar pull-right"
                    data-selected-dates="<?php echo implode(',', $usedRequestDates); ?>"
                    data-show-date="<?php echo end($usedRequestDates); ?>"
                ><span class="icon-eye-open"></span></button>
            </td>
        </tr>
        </tbody>
    </table>
</div>
