<div class="checking-history-header">
    Check IN/OUT for: "<span><?php echo $this->date; ?></span>"
</div>

<?php if ( ! empty($this->checkins)): ?>
    <div class="span4 checkins-table-container">
    <table class="table table-bordered table-striped table-small-td">
        <thead>
        <tr>
            <th>
                Check IN
            </th>
            <th>
                Check OUT
            </th>
            <?php if ($this->isAdmin): ?>
            <?php endif; ?>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($this->checkins as $checkin): ?>
            <?php $overtime = ''; ?>
            <tr>
                <td>
                    <?php echo (string)$checkin['check_in']; ?>
                </td>
                <td>
                    <?php echo (string)$checkin['check_out']; ?>
                </td>
                <?php if ($this->isAdmin): ?>
                    <input type="checkbox" class="approve-overtime" checked="checked" data-checkin-id="<?php echo $checkin['id']; ?>" />
                <?php endif; ?>
            </tr>
        <?php endforeach;?>
        <tr></tr>
        </tbody>
    </table>
    </div>
<?php else: ?>
    <div class="checking-history-header">
        No checkins in this day.
    </div>
<?php endif; ?>