<?php /********** INCLUDE CALENDAR MODULE *****************/ ?>
<?php $this->headScript()->appendFile($this->baseUrl() . '/js/calendar.js'); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl() . '/css/calendar.css'); ?>

<input type="hidden" id="date-today" value="<?php echo $this->today; ?>" />

<div class="span11">
    <table class="table table-bordered table-striped table-small-td">
        <thead>
        <tr>
            <th class="span3">&nbsp;</th>
            <th class="span2">Check IN/OUT</th>
            <th class="span2">Datum</th>
            <th class="span2">Check IN time</th>
            <th class="span2">Check OUT time</th>
        </tr>
        </thead>
        <tbody>
        <?php if ( ! empty($this->me)): ?>
            <?php
                $this->user  = $this->me + $this->lastCheck;
                $this->user['is_admin'] = false;
                $this->group = array();
            ?>
            <?php echo $this->render('checking/_blocks/user_row.phtml'); ?>
        <?php endif; ?>
        </tbody>
    </table>
</div>


<?php if (empty($this->users)): ?>
Error! No users.
<?php else: ?>
<?php $this->headScript()->appendFile($this->baseUrl() . '/js/checking.js'); ?>

<div class="span11">

    <?php /* THIS IS DEFAULT GROUP. GROUP WITH ALL USERS *
    <table class="table table-bordered table-striped table-small-td">
        <thead>
        <tr>
            <th class="span3">Naam</th>
            <th class="span2">Check IN/OUT</th>
            <th class="span2">Datum</th>
            <th class="span2">Check IN time</th>
            <th class="span2">Check OUT time</th>
        </tr>
        </thead>
        <tbody>
            <?php foreach($this->users as $user): ?>
            <?php $this->user = $user; ?>
            <?php echo $this->render('checking/_blocks/user_row.phtml'); ?>
            <?php endforeach; ?>
        </tbody>
    </table>
    <?php */ ?>

    <?php foreach($this->groups as $group): ?>
        <?php $isAdmin = (bool)$group['is_admin']; ?>
    <table class="table table-bordered table-striped table-small-td">
        <thead>
        <tr <?php if ( ! empty($group['color'])): ?>style="background-color: #<?php echo $group['color']; ?>;"<?php endif; ?>>
            <th class="span3"><?php echo $group['group_name']; ?></th>
            <th class="span2">Check IN/OUT</th>
            <th class="span2">Datum</th>
            <th class="span2">Check IN time</th>
            <th class="span2">Check OUT time</th>
        </tr>
        </thead>
        <tbody>
            <?php if ( ! empty($group['users'])): ?>
            <?php foreach($group['users'] as $user): ?>
            <?php $this->user  = $user; ?>
            <?php $this->user['is_admin'] = $isAdmin; ?>
            <?php $this->group = $group; ?>
            <?php echo $this->render('checking/_blocks/user_row.phtml'); ?>
            <?php endforeach; ?>
            <?php else: ?>
            <tr><td colspan="5">No users in this group</td></tr>
            <?php endif; ?>
        </tbody>
    </table>
    <?php endforeach; ?>

</div>

<?php endif; ?>

<div class="modal hide span12 popup" id="show-user-checking-modal">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">X</button>
        <h3>User Checking</h3>
    </div>
    <div class="modal-body">
        <div class="user-calendar-container">
            <div class="pull-left" id="user-checking-calendar-container">
                <div class="">
                    <div
                        class="module-calendar"
                        data-old-selected-dates=""
                        data-selected-dates=""
                        data-blocked-dates="<?php echo $this->date; ?>"
                        data-container-id="user-checking-calendar-container"
                        data-editable="0"
                        ></div>
                </div>
            </div>
        </div>
        <div class="user-checking-container"></div>
    </div>
    <div class="modal-footer">
        <div class="pull-left">
            Work hours plan: <span class="work-hours-plan"><?php echo $this->workHoursPlan; ?></span><br />
            Work hours done: <span class="work-hours-done"><?php echo $this->workHoursDone; ?></span><br />
            Work hours overtime: <span class="work-hours-overtime"><?php echo $this->workHoursOvertime; ?></span><br />
        </div>
        <div class="pull-right save-checkin-data-button">
            <input id="save-checkin-data-button" type="button" class="btn btn-primary" value="Save" />
        </div>
    </div>
</div>
