<?php if (empty($this->users)): ?>
Error! No users.
<?php else: ?>
<?php $this->headScript()->appendFile('/js/checking.js'); ?>

    <?php
    $colors = Application_Model_Group::getAllowedColors();
    ?>

<div class="span11">

    <table class="table table-bordered table-striped table-small-td">
        <thead>
        <tr>
            <th class="span3">Naam</th>
            <th class="span2">Check IN/OUT</th>
            <th class="span2">Datum</th>
            <th class="span2">Check IN time</th>
            <th class="span2">Check OUT time</th>
        </tr>
        </thead>
        <tbody>
            <?php if ( ! empty($group['users'])): ?>
            <?php foreach($this->users as $user): ?>
            <?php $this->user = $user; ?>
            <?php echo $this->render('checking/_blocks/user_row.phtml'); ?>
            <?php endforeach; ?>
            <?php else: ?>
            <tr><td colspan="5">No users in this group</td></tr>
            <?php endif; ?>
        </tbody>
    </table>

    <?php foreach($this->groups as $group): ?>
    <table class="table table-bordered table-striped table-small-td">
        <thead>
        <tr <?php if ( ! empty($group['color'])): ?>style="background-color: #<?php echo $group['color']; ?>;"<?php endif; ?>>
            <th class="span3"><?php echo $group['group_name']; ?></th>
            <th class="span2">Check IN/OUT</th>
            <th class="span2">Datum</th>
            <th class="span2">Check IN time</th>
            <th class="span2">Check OUT time</th>
        </tr>
        </thead>
        <tbody>
            <?php if ( ! empty($group['users'])): ?>
            <?php foreach($group['users'] as $user): ?>
            <?php $this->user  = $user; ?>
            <?php $this->group = $group; ?>
            <?php echo $this->render('checking/_blocks/user_row.phtml'); ?>
            <?php endforeach; ?>
            <?php else: ?>
            <tr><td colspan="5">No users in this group</td></tr>
            <?php endif; ?>
        </tbody>
    </table>
    <?php endforeach; ?>

</div>

<?php endif; ?>