<fieldset>
    <?php echo $this->element->userId; ?>
    <legend>Change password Form</legend>
    <div class="control-group">
        <label class="control-label" for="password_old">Current password:</label>
        <div class="controls">
            <?php echo $this->element->password_old->setAttrib('placeholder', 'Current password')->setAttrib('class', 'input-medium') ?>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="password">New password:</label>
        <div class="controls">
            <?php echo $this->element->password->setAttrib('placeholder', 'New password')->setAttrib('class', 'input-medium') ?>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="password_repeat">Repeat:</label>
        <div class="controls">
            <?php echo $this->element->password_repeat->setAttrib('placeholder', 'Password repeat')->setAttrib('class', 'input-medium') ?>
        </div>
    </div>
    <div class="form-actions">
        <?php echo $this->formButton('submit', 'Register', array('class' => 'btn btn-primary pull-center', 'type' => 'submit')) ?>
    </div>
</fieldset>