<div class="control-group">
    <label class="control-label" for="email">Email *:</label>
    <div class="controls">
        <?php echo $this->element->email->setAttrib('placeholder', 'Email')->setAttrib('class', 'input-medium') ?>
        <span class="help-inline"></span>
    </div>
</div>
<div class="control-group">
    <label class="control-label" for="password">Password *:</label>
    <div class="controls">
        <?php echo $this->element->password->setAttrib('placeholder', 'Password')->setAttrib('class', 'input-medium') ?>
        <span class="help-inline"></span>
    </div>
</div>
<div class="control-group">
    <label class="control-label" for="password">Full name:</label>
    <div class="controls">
        <?php echo $this->element->full_name->setAttrib('placeholder', 'Full name')->setAttrib('class', 'input-medium') ?>
        <span class="help-inline"></span>
    </div>
</div>
<div class="control-group">
    <label class="control-label" for="phone">Phone:</label>
    <div class="controls">
        <?php echo $this->element->phone->setAttrib('placeholder', 'Phone')->setAttrib('class', 'input-medium') ?>
        <span class="help-inline"></span>
    </div>
</div>
<div class="control-group">
    <label class="control-label" for="address">Address:</label>
    <div class="controls">
        <?php echo $this->element->address->setAttrib('placeholder', 'Address')->setAttrib('class', 'input-medium') ?>
        <span class="help-inline"></span>
    </div>
</div>
<div class="control-group">
    <label class="control-label" for="emergency_phone">Emergency Phone:</label>
    <div class="controls">
        <?php echo $this->element->emergency_phone->setAttrib('placeholder', 'Emergency Phone')->setAttrib('class', 'input-medium') ?>
        <span class="help-inline"></span>
    </div>
</div>
<div class="control-group">
    <label class="control-label" for="emergency_full_name">Emergency Full name:</label>
    <div class="controls">
        <?php echo $this->element->emergency_full_name->setAttrib('placeholder', 'Emergency Full name')->setAttrib('class', 'input-medium') ?>
        <span class="help-inline"></span>
    </div>
</div>
<div class="control-group">
    <label class="control-label" for="birthday">Birthday:</label>
    <div class="controls">
        <?php echo $this->element->birthday->setAttrib('placeholder', 'DD-MM-YYYY')->setAttrib('class', 'input-medium') ?>
        <span class="help-inline"></span>
    </div>
</div>
<div class="control-group">
    <label class="control-label" for="owner">Owner:</label>
    <div class="controls">
        <?php echo $this->element->owner->setAttrib('placeholder', 'Owner')->setAttrib('class', 'input-medium') ?>
        <span class="help-inline"></span>
    </div>
</div>
