<?php
$status = new Application_Model_Status();
$statuses = $status->getAllStatus();

$selectedStatus1 = $this->element->status1->getValue();
$selectedStatus2 = $this->element->status2->getValue();
?>
<label class="control-label" for="color">Day color:</label>
<div class="day-color-selector">
    <?php foreach ($statuses as $status): ?>
    <div class="day-status-color <?php if ($selectedStatus1 == $status['id'] || $selectedStatus2 == $status['id']): ?> active<?php endif; ?>" style="background-color: #<?php echo $status['color_hex']; ?>;" data-color="<?php echo $status['color']; ?>"><?php echo $status['color']; ?></div>
    <?php endforeach; ?>
</div>