<div class="alert alert-error" style="display: none;"></div>
<div class="alert alert-success" style="display: none;"></div>
<?php echo $this->element->id; ?>
<?php echo $this->element->user_id; ?>
<?php echo $this->element->group_id; ?>
<?php echo $this->element->date; ?>
<?php echo $this->element->status1; ?>
<?php echo $this->element->status2; ?>
<?php
$status = new Application_Model_Status();
$statuses = $status->getAllStatus();

$selectedStatus1 = $this->element->status1->getValue();
$selectedStatus2 = $this->element->status2->getValue();
$this->selectedStatus1 = $selectedStatus1;
$this->selectedStatus2 = $selectedStatus2;
$additionalStyleForInput = ' style="margin: 0px;" '; //I can't replace common style
?>
<?php echo $this->element->time_start; ?>
<?php echo $this->element->time_end; ?>

<div><h3>Set time and day color</h3></div>

<table class="table table-bordered table-condensed table-striped work-time">
    <thead>
    <tr>
        <th >Hour type</th><th >Color</th><th >Time start</th><th >Time end</th><th >Holiday</th>
    </tr>
    </thead>

        <?php for ($i = 2; $i < 8; $i++): ?>
        <?php if  ($selectedStatus1 == 2 || $i == 7) ://green color status or overtime?>
            <tr>
                <td>
                    <?php echo $statuses[$i]['description']  ?>
                </td>
                <td style="background-color: #<?php echo $statuses[$i]['color_hex']?>;">
                    <div   style="width: 100px;"></div>
                </td>
                <?php
                if  ($i == 3 || $i == 2) {
                    $disabledInput =  ' disabled="disabled "';
                } else {
                    $disabledInput =  '';
                }
                ?>
                    <td>
                        <div class="input-time">
                            <input type="text" value="<?php echo @$startHourValue; ?>" <?php echo $additionalStyleForInput . $disabledInput ?>  name="start_hour" class="set-time-hour-status start-hour set-time-hour-field">:
                            <input type="text" value="<?php echo @$startMinValue; ?>"  <?php echo $additionalStyleForInput . $disabledInput?> name="start_min" class="set-time-min-status start-min">
                        </div>
                    </td>
                    <td>
                        <div class="input-time">
                            <input type="text" value="<?php echo @$endHourValue; ?>" <?php echo $additionalStyleForInput . $disabledInput ?>  name="end_hour" class="set-time-hour-status end-hour">:
                            <input type="text" value="<?php echo @$endMinValue; ?>" <?php echo $additionalStyleForInput . $disabledInput ?>  name="end_min" class="set-time-min-status end-min">
                        </div>
                    </td>
                <td></td>
            </tr>
        <?php endif; ?>
        <?php endfor; ?>
</table>

