<div class="alert alert-error" style="display: none;"></div>
<div class="alert alert-success" style="display: none;"></div>
<?php echo $this->element->id; ?>
<?php echo $this->element->color; ?>
<div class="control-status">
    <label class="control-label" for="description">Status description</label>
    <?php echo $this->element->description->setAttrib('class', 'input-medium') ?>
</div>
<div class="control-status">
    <label class="control-label" for="long_description">Status long Description</label>
    <?php echo $this->element->long_description->setAttrib('rows', '3') ?>
    <?php //echo $this->element->long_description; ?>
</div>
<div class="control-status">
    <label class="control-label" for="alert_description">Status Alert Description</label>
    <?php echo $this->element->alert_description->setAttrib('rows', '3') ?>
    <?php //echo $this->element->long_description; ?>
</div>
<div class="control-status">
    <label class="is-holiday" for="is_holiday">Status is holiday
    <?php
        $statusId = $this->element->id->getAttrib('_value');
        if ($statusId == 1 || $statusId == 2 || $statusId == 7 || $statusId == 3) {
            echo $this->element->is_holiday->setAttrib('disabled', 'disabled');
        } else {
            echo $this->element->is_holiday;
        }
    ?>

    </label>
</div>
<?php  $w =$this->element->id->getAttrib('_value'); ?>

<?php echo $this->render('forms/group-color.phtml'); ?>