<div class="alert alert-error" style="display: none;"></div>
<div class="alert alert-success" style="display: none;"></div>
<?php echo $this->element->id; ?>
<?php echo $this->element->color; ?>
<table>
    <tr>
        <td>
            <label class="control-label" for="time_start">Time start</label>
            <div class="input-append bootstrap-timepicker-component">
            <?php echo $this->element->time_start->setAttrib('class', 'timepicker-start input-mini') ?>
                <span class="add-on">
                    <i class="icon-time"></i>
                </span>
            </div>
        </td>
        <td colspan="2">
            <label class="control-label" for="time_end">Time end</label>
            <div class="input-append bootstrap-timepicker-component">
                <?php echo $this->element->time_end->setAttrib('class', 'timepicker-end input-mini') ?>
                <span class="add-on">
                    <i class="icon-time"></i>
                </span>
            </div>
        </td>
        <td>
            <label class="control-label" for="time_exclude">Time exclude</label>
            <div class="input-append bootstrap-timepicker-component">
                <?php echo $this->element->time_exclude->setAttrib('class', 'timepicker-exclude input-mini') ?>
                <span class="add-on">
                    <i class="icon-time"></i>
                </span>
            </div>
        </td>
    <tr>
</table>
<?php echo $this->render('forms/day-status-color.phtml'); ?>
