<div class="alert alert-error" style="display: none;"></div>
<div class="alert alert-success" style="display: none;"></div>
<?php echo $this->element->id; ?>
<?php echo $this->element->color_hex; ?>
<div class="control-status">

    <table class="table-bordered table-condensed table-striped form-edit-day">
        <thead>
        <tr>
            <th >Time start</th><th ></th><th >Time end</th>
        </tr>
        </thead>
        <tr  class="work-time">
            <td>
                <div class="input-time">
                    <input type="text" value="<?php echo @$statusData['split_time_start']['hour']; ?>" class="set-time-hour-status start-hour set-time-hour-field"  name="start_hour" class="set-time-hour-status start-hour set-time-hour-field">:
                    <input type="text" value="<?php echo @$statusData['split_time_start']['min']; ?>" class="set-time-hour-status start-hour set-time-hour-field" name="start_min" class="set-time-min-status start-min set-time-mins-field">
                </div>
            </td>
            <td>
            </td>
            <td>
                <div class="input-time">
                    <input type="text" value="<?php echo @$statusData['split_time_end']['hour']; ?>" class="set-time-hour-status start-hour set-time-hour-field"  name="end_hour" class="set-time-hour-status end-hour set-time-hour-field">:
                    <input type="text" value="<?php echo @$statusData['split_time_end']['min']; ?>" class="set-time-hour-status start-hour set-time-hour-field"  name="end_min" class="set-time-min-status end-min set-time-mins-field">
                </div>
            </td>
        </tr>
    </table>
    <label class="control-label" for="description">Interval description</label>
    <?php echo $this->element->description->setAttrib('class', 'input-medium') ?>
</div>
<?php  $w =$this->element->id->getAttrib('_value'); ?>

<?php echo $this->render('forms/interval-color.phtml'); ?>