<div class="alert alert-error" style="display: none;"></div>
<div class="alert alert-success" style="display: none;"></div>
<?php echo $this->element->id; ?>
<?php echo $this->element->user_id; ?>
<?php echo $this->element->group_id; ?>
<?php echo $this->element->date; ?>
<?php echo $this->element->status1; ?>
<?php echo $this->element->status2; ?>
<?php
$status = new Application_Model_Status();
$statuses = $status->getAllStatus();

$selectedStatus1 = $this->element->status1->getValue();
$selectedStatus2 = $this->element->status2->getValue();
$this->selectedStatus1 = $selectedStatus1;
$this->selectedStatus2 = $selectedStatus2;
?>
<?php echo $this->element->time_start; ?>
<?php echo $this->element->time_end; ?>
<?php if (0 && $selectedStatus1 != 1) ://white color status //switch off because broken logic?>
<div><h3>Day Work Time</h3></div>
<table>
    <tr>
        <td>
            <label class="control-label" for="time_start">Time start</label>
            <div class="input-append bootstrap-timepicker-component">
                <?php echo $this->element->time_start->setAttrib('class', 'timepicker-start input-mini') ?>
                <span class="add-on">
                    <i class="icon-time"></i>
                </span>
            </div>
        </td>
        <td>
            <label class="control-label" for="time_end">Time end</label>
            <div class="input-append bootstrap-timepicker-component">
                <?php echo $this->element->time_end->setAttrib('class', 'timepicker-end input-mini') ?>
                <span class="add-on">
                    <i class="icon-time"></i>
                </span>
            </div>
        </td>
    <tr>
</table>
<?php endif; ?>
<div><h3>Set time and day color</h3></div>

<table>
    <tr>
        <td>
            <label class="control-label" for="time_exclude">Time Start</label>
            <div class="input-append bootstrap-timepicker">
                <?php echo $this->element->time_start2->setAttrib('class', 'timepicker-start2 input-mini') ?>
            </div>
        </td>
        <td>
            <label class="control-label" for="time_exclude">Time end</label>
            <div class="input-append bootstrap-timepicker">
                <?php echo $this->element->time_end2->setAttrib('class', 'timepicker-end2 input-mini') ?>
            </div>
        </td>
    <tr>
</table>
<?php if ($selectedStatus1 != 1) ://white color status ?>
<button type="button" class="btn  btn-primary" id="apply-time-full-day" >Apply for full day</button>
<?php endif; ?>
<?php if  ($selectedStatus1 == 2) ://green color status ?>
<div class="day-color-selector">
    <?php
        $this->status = $statuses[4];
        echo $this->render('forms/color_button.phtml');
        $this->status = $statuses[5];
        echo $this->render('forms/color_button.phtml');
        $this->status = $statuses[6];
        echo $this->render('forms/color_button.phtml');
        $this->status = $statuses[7];
        echo $this->render('forms/color_button.phtml');
    ?>
</div>
<?php elseif ($selectedStatus1 == 1) ://white color status ?>
<?php
    $this->status = $statuses[7];
    //$this->selectedStatus2 = 7;
    echo $this->render('forms/color_button.phtml');
?>
<?php endif; ?>