<fieldset>
    <legend>Login Form</legend>
    <div class="control-group">
        <label class="control-label" for="email">Login:</label>
        <div class="controls">
            <?php echo $this->element->email->setAttrib('placeholder', 'Email')->setAttrib('class', 'input-medium') ?>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="password">Password:</label>
        <div class="controls">
            <?php echo $this->element->password->setAttrib('placeholder', 'Password')->setAttrib('class', 'input-medium') ?>
        </div>
    </div>
    <div class="form-actions">
        <?php echo $this->formButton('submit', 'Login', array('class' => 'btn btn-primary pull-center', 'type' => 'submit')) ?>
    </div>
</fieldset>