<fieldset>
    <legend>Register Form</legend>
    <div class="control-group">
        <label class="control-label" for="email">Login:</label>
        <div class="controls">
            <?php echo $this->element->email->setAttrib('placeholder', 'Email')->setAttrib('class', 'input-medium') ?>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="password">Password:</label>
        <div class="controls">
            <?php echo $this->element->password->setAttrib('placeholder', 'Password')->setAttrib('class', 'input-medium') ?>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="password_repeat">Repeat:</label>
        <div class="controls">
            <?php echo $this->element->password_repeat->setAttrib('placeholder', 'Password repeat')->setAttrib('class', 'input-medium') ?>
        </div>
    </div>
    <hr>
    <div class="control-group">
        <label class="control-label" for="first_name">First Name:</label>
        <div class="controls">
            <?php echo $this->element->first_name->setAttrib('placeholder', 'First Name')->setAttrib('class', 'input-medium') ?>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="last_name">Last Name:</label>
        <div class="controls">
            <?php echo $this->element->last_name->setAttrib('placeholder', 'Last Name')->setAttrib('class', 'input-medium') ?>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="role">Role:</label>
        <div class="controls">
            <?php echo $this->element->role->setAttrib('class', 'input-medium') ?>
        </div>
    </div>
    <div class="form-actions">
        <?php echo $this->formButton('submit', 'Register', array('class' => 'btn btn-primary pull-center', 'type' => 'submit')) ?>
    </div>
</fieldset>