<div
        class="row user_row width-full"
        id="<?php echo $this->group['id']; ?>"
        data-user-id="<?php echo $this->group['id']; ?>"
        >
    <div class="user_row_container">
        <span class="span4 block-history">
            <a href="<?php echo $this->url(array('action' => 'get-more-history'), 'planner', true); ?>" class="no-action show-more-history">History</a>
                <div class="history-container-scrollable">
                    <div class="history-container">
                        <?php //echo $this->render('_blocks/history.phtml'); ?>
                    </div>
                </div>
        </span>

        <?php $this->users = $this->group['users']; ?>
        <?php echo $this->render('_blocks/week_details.phtml'); ?>

    </div>
    <?php //echo $this->render('_blocks/user_options.phtml'); ?>
</div>