<?php
    /*** PREPARE DATA ***/
    $headerWeeks         = '';
    $historyRows         = array();
    $emptyRow            = '';
    foreach ($this->historyDateWeekYear as $week => $year) {
        $headerWeeks         .= '<th>
            <a href="' . $this->url(array('controller' => 'planning', 'action' => 'index', 'year' => $year, 'week' => $week), 'planner', true). '" class="get-week-details" data-year="' . $year . '" data-week="' . $week . '" title="' . $week . '">
                Week ' . $week . '
            </a>
        </th>';

        $emptyRow            .= '<td>&nbsp;</td>';
    }
?>

<table class="history table table-bordered table-condensed table-striped" style="width: 300px; margin-right: 20px; float: left;">
    <thead>
    <tr class="week-table-header">
        <?php echo $headerWeeks; ?>
    </tr>
    <tr  style="background-color: #<?php echo $this->group['color'];?>" class="week-table-header">
        <?php echo $emptyRow; ?>
    </tr>
    </thead>
    <tbody>
    <?php if (empty($this->users)): ?>
    <td colspan="4" class="user-not-found">
        No users history
    </td>
    <?php else: ?>
    <?php foreach($this->users as $week => $row): ?>
    <tr>
        <?php foreach($row['history'] as $week => $workTime): ?>
        <td><div class="show-tooltip"  title="zz<?php // echo  $title ?>" ><?php echo $workTime; ?></div></td>
        <?php endforeach; ?>
    </tr>
    <?php endforeach; ?>
    <?php endif; ?>
    </tbody>
</table>
