<?php
    $week = $this->weekTasks['week'];
    $date = date('Y-m-d', strtotime($this->weekTasks['year'] . 'W' . $this->weekTasks['week']));
?>
<tr>
    <th colspan="5"><?php echo $this->group['group_name']; ?></th>
    <th>
        <a href="<?php echo $this->url(array('action' => 'get-week-details'), 'planner', true); ?>" rel="tooltip" class="bootstrab-tooltip no-action get-week-details" data-original-title="Look next week" data-year="<?php echo $this->nextWeekYear; ?>" data-week="<?php echo $this->nextWeek; ?>" title="<?php echo $date; ?>">
            Week <?php echo $week; ?>
        </a>
    </th>
</tr>