<?php
 /**
  * $this->weekTasks['year']
  * $this->weekTasks['week']
  * $this->weekTasks['tasks']
  * $this->weekTasks['fulfilled']
  * $this->user['tasksIds']
  */
?>
<span
    class="span10 block-week-details week-details main-data-container user-id-<?php echo $this->group['id']; ?> year-<?php echo $this->weekTasks['year']; ?> week-<?php echo $this->weekTasks['week']; ?>"
    data-year="<?php echo $this->weekTasks['year']; ?>"
    data-week="<?php echo $this->weekTasks['week']; ?>"
    data-userId="<?php echo $this->group['id']; ?>"
>
    <br />

    <div class="week-details-container">
        <table class="table table-bordered table-condensed table-striped week-table">

            <thead>

            <?php echo $this->render('_blocks/week_details_header.phtml'); ?>

            <tr class="week-table-header">
                <th class="week-table-header-task">Taak/Dag</th>
                <th class="week-table-header-monday week-table-header-day">Maandag</th>
                <th class="week-table-header-tuesday week-table-header-day">Dinsdag</th>
                <th class="week-table-header-wednesday week-table-header-day">Woensdag</th>
                <th class="week-table-header-thursday week-table-header-day">Donderdag</th>
                <th class="week-table-header-friday week-table-header-day">Vrijdag</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->users as $user): ?>
                <?php $this->user = $user; ?>
                <?php $this->task   = null; ?>
                <?php echo $this->render('_blocks/week_details_plan.phtml'); ?>
            <?php endforeach; ?>

            <?php echo $this->render('_blocks/add_plan_link.phtml'); ?>

            </tbody>
        </table>
    </div>

</span>