<?php if ( ! empty($this->group)): ?>
    <?php if ( ! empty($this->users)): ?>
        <?php foreach ($this->users as $user): ?>
            <?php $this->user = $user; ?>
            <?php echo $this->render('group-settings/_blocks/user_planning.phtml'); ?>
        <?php endforeach; ?>
    <?php else: ?>
        No Users in this group.
    <?php endif; ?>

<?php else : ?>
    <span class="alert alert-error">Error! Wrong group ID!</span>
<?php endif; ?>