<?php $this->headScript()->appendFile('/js/group-settings.js'); ?>
<?php /********** INCLUDE CALENDAR MODULE *****************/ ?>
<?php $this->headScript()->appendFile('/js/calendar.js'); ?>
<?php $this->headLink()->appendStylesheet('/css/calendar.css'); ?>

<?php
$maxFreePeopleAction = $this->url(array('controller' => 'group-settings', 'action' => 'save-group-setting-max-free-people'), 'planner', true);
?>

<div class="span12">

    <table class="table table-bordered group-settings-table">
        <thead>
        <tr>
            <th class="span3">
                Settings general
            </th>
            <th class="span2">
                Holiday numbers
            </th>
            <th class="span3">
                Exception period/numbers
            </th>
            <th class="span4">
                Alert when more then maximum
                <a href="#" class="show-tooltip no-action" data-original-title="by illness or manual overrule"><i class="icon-info-sign"></i></a>
            </th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>
                &nbsp;
            </td>
            <td>
                <div class="input-append">
                    <form method="POST" class="form-mini mini-ajax-form" id="group-<?php echo $this->generalGroup['id']; ?>-max-free-people" action="<?php echo $maxFreePeopleAction; ?>">
                        <div class="input-append control-group">
                            <input type="hidden" name="group" value="0">
                            <?php
                            $maxFreePeople = '';
                            if (isset($this->generalGroup['settings']['max_free_people'])) {
                                $maxFreePeople = (int)$this->generalGroup['settings']['max_free_people'];
                            }
                            ?>
                            <input type="text" name="max_free_people" class="span1 rule-int btn-mini" value="<?php echo $maxFreePeople; ?>">
                            <button class="btn btn-success btn-no-text button-submit" type="button" data-form="group-<?php echo $this->generalGroup['id']; ?>-max-free-people"><i class="icon-ok icon-white"></i></button>
                        </div>
                    </form>
                </div>
            </td>
            <td>
                <?php
                $this->group = $this->generalGroup;
                echo $this->render('group-settings/_blocks/group_exceptions.phtml');
                ?>
            </td>
            <td>
                <div class="input-append">
                    <form method="POST" class="form-mini save-alert-over-limit-form mini-ajax-form" action="/group-settings/save-alert-over-limit">
                        <input type="hidden" name="group" value="0">
                        <input type="text" class="span1 rule-int btn-mini alert-over-limit" value="<?php echo (int)$this->generalGroup['settings']['alert_over_limit_free_people']; ?>" name="alert_over_limit_free_people">
                        <button class="btn btn-success btn-no-text" type="submit"><i class="icon-ok icon-white"></i></button>
                    </form>
                </div>
            </td>
        </tr>
        </tbody>
    </table>

</div>

<div class="span8">

    <table class="table table-bordered group-settings-table">
        <thead>
        <tr>
            <th class="span3">
                <a class="btn btn-mini btn-success create-group no-action" href="<?php echo $this->url(array('controller' => 'group-settings', 'action' => 'get-edit-group-form'), 'planner', true); ?>">
                    <i class="icon-plus-sign icon-white"></i>
                </a>
                Group
            </th>
            <th class="span2">
                Holiday numbers
            </th>
            <th class="span3">
                Exception period/numbers
            </th>
        </tr>
        </thead>
        <tbody>
        <?php if ( ! empty($this->groups)): ?>
            <?php foreach ($this->groups as $group): ?>
                <tr>
                    <td style="background-color: #<?php echo $group['color']; ?>">
                        <a href="<?php echo $this->url(array('controller' => 'group-settings', 'action' => 'get-edit-group-form'), 'planner', true); ?>" class="no-action edit-group btn btn-mini" data-group-id="<?php echo $group['id']; ?>" data-group-name="<?php echo $group['group_name']; ?>">
                            <i class="icon-cog"></i>
                        </a>
                        <?php echo $group['group_name']; ?>
                    </td>
                    <td>
                        <form method="POST" class="form-mini mini-ajax-form" id="group-<?php echo $group['id']; ?>-max-free-people" action="<?php echo $maxFreePeopleAction; ?>">
                            <div class="input-append control-group">
                                <input type="hidden" name="group" value="<?php echo $group['id']; ?>">
                                <?php
                                    $maxFreePeople = '';
                                    if (isset($group['settings']['max_free_people'])) {
                                        $maxFreePeople = (int)$group['settings']['max_free_people'];
                                    }
                                ?>
                                <input type="text" name="max_free_people" class="span1 rule-int btn-mini" value="<?php echo $maxFreePeople; ?>">
                                <button class="btn btn-success btn-no-text button-submit" type="button" data-form="group-<?php echo $group['id']; ?>-max-free-people"><i class="icon-ok icon-white"></i></button>
                            </div>
                        </form>
                    </td>
                    <td>
                    <?php
                        $this->group = $group;
                        echo $this->render('group-settings/_blocks/group_exceptions.phtml');
                    ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php else: ?>
        <tr>
            <td colspan="3">No groups</td>
        </tr>
        <?php endif; ?>
        </tbody>
    </table>

</div>

<div class="span12 normal-user-holidays">
    <div class="input-prepend input-append">
        <span class="add-on">Number of holiday hours based on 100% (40 hours) working week:</span>
        <input type="text" class="span1 rule-int btn-mini" name="default_total_free_hours" id="default_total_free_hours" value="<?php echo $this->defaultTotalFreeHours; ?>">
        <button class="btn btn-success btn-no-text save-default-total-free-hours" type="button"><i class="icon-ok icon-white"></i></button>
    </div>
</div>

<div class="span12 regular-holidays">
    <table class="">
        <tbody>
        <tr>
            <td>
                <?php
                    $holidays = array();
                    foreach ($this->generalHolidays as $holiday) {
                        $date = $holiday['holiday_date'];
                        $holidays[$date] = $date;
                    }
                ?>
                <button
                    class="btn btn-mini btn-success create-holiday"
                    data-old-selected-dates="<?php echo implode(',', $holidays); ?>"
                ><i class="icon-plus-sign icon-white"></i></button>
                Special free days per year
                <a href="#" class="show-tooltip no-action" data-original-title="Christmas, Eastern, etc."><i class="icon-info-sign"></i></a>:
            </td>
            <td style="width: 600px;">
                <?php foreach ($this->generalHolidays as $holiday): ?>
                    <?php
                        try {
                            $date = new DateTime($holiday['holiday_date']);
                            $date = $date->format('d.m.Y');
                        } catch (Exception $e) { $date = $start['holiday_date']; }
                    ?>
                    <span class="label label-info">
                        <?php echo $date; ?> <?php echo $holiday['holiday_name']; ?>
                        <a href="#" class="show-tooltip no-action remove-holiday" data-original-title="Remove" data-holiday="<?php echo $holiday['id']; ?>" data-holiday-name="<?php echo $holiday['holiday_name']; ?>">
                            <i class="icon-remove icon-white"></i>
                        </a>
                    </span>
                <?php endforeach; ?>
            </td>
        </tr>
        </tbody>
    </table>
</div>

<div class="span12 group-work-days-planning width-full">
    <div class="header">
        <strong>Select group for planning:</strong>
        <select name="group-planning" id="group-planning">
            <option value="">Please selecte group...</option>
            <?php foreach ($this->groups as $group): ?>
                <option value="<?php echo $group['id']; ?>" style="background-color: #<?php echo $group['color']; ?>;" data-group-color="<?php echo $group['color']; ?>"><?php echo $group['group_name']; ?></option>
            <?php endforeach; ?>
        </select>
    </div>
    <div class="planning-body"></div>
</div>

<div class="modal hide fade modal-edit-group">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">X</button>
        <h3 class="header-create-group">Create group</h3>
        <h3 class="header-edit-group">Edit group: <span class="tmpl-group-name"></span></h3>
    </div>
    <div class="modal-body">

    </div>
    <div class="modal-footer">
        <a type="button" class="btn btn-danger button-delete-group no-action" data-group-id="" href="<?php echo $this->url(array('controller' => 'group-settings', 'action' => 'delete-group'), 'planner', true); ?>">Delete</a>
        <button type="button" class="btn btn-primary button-submit" data-form="form-edit-group">Save</button>
    </div>
</div>

<div class="modal hide popup" id="edit-group-exceptions-modal">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">X</button>
        <h3>Group exceptions</h3>
    </div>
    <div class="modal-body">
        <div id="exceptions-calendar-container">
        <div
            class="module-calendar"
            data-selected-dates=""
            data-container-id="exceptions-calendar-container"
        ></div>
        </div>
        <div class="pull-left">
            <div>
                <span class="param-name">Geselecteerd is:</span> <span class="exceptions-text"></span>
            </div>
            <input type="hidden" name="edit-dates" value="" class="edit-dates">
            <input type="hidden" name="group" value="" class="group-id">
            Max. free people: <input type="text" name="max_free_people" value="0" class="max_free_people">
        </div>
    </div>
    <div class="modal-footer">
        <button class="btn btn-success" id='submit-group-exceptions'>Save</button>
    </div>
</div>

<div class="modal hide popup" id="add-group-holidays-modal">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">X</button>
        <h3>Regular holidays</h3>
    </div>
    <div class="modal-body">
        <div id="holidays-calendar-container">
            <div
                class="module-calendar"
                data-selected-dates=""
                data-container-id="holidays-calendar-container"
                data-editable="1"
                data-max-select="1"
            ></div>
        </div>
        <div class="pull-left">
            <span class="help-block">* You can select only one day</span>
            <input type="hidden" name="group" value="" class="group-id">
            Holiday name: <input type="text" name="holiday_name" value="0" class="holiday_name">
        </div>
    </div>
    <div class="modal-footer">
        <button class="btn btn-success" id='submit-group-holidays'>Save</button>
    </div>
</div>